### PR TITLE
Compressing and flipping min/max.

### PR DESCRIPTION
**Pull request by agamemnus**
1) Removed a bunch of empty lines for readability...
2) Min and max seemed to be flipped. Practically, it makes no difference.
3) Did `if (min < value) { min = value; } else if (max > value) { max = value; }`, since value cannot be greater than min and less than max at the same time.

### CODE REVIEW

**Comment by katspaugh** [comment]
Took me some minutes to realize this PR doesn't do anything useful. Let's not introduce unnecessary stylistic changes.

**Comment by agamemnus** [comment]
It will allow a better understanding of the code for more changes later
(see
https://github.com/katspaugh/wavesurfer.js/issues/1082#issuecomment-306976656)
and because min and max are flipped...

**Comment by katspaugh** [comment]
I'm not sure why you think `max` and `min` are flipped (and should be reversed). Can you explain?

**Comment by agamemnus** [comment]
I just looked at it again and it turns out that I got psyched out by the
code. They could not be reversed.

**Comment by agamemnus** [comment]
Should*

**Pull request closed without merging**
