### PR TITLE
Create invertTransparency option to MultiCanvas.

### PR DESCRIPTION
**Pull request by agamemnus**
Blocked by https://github.com/katspaugh/wavesurfer.js/pull/1132. (I am again not sure how the merging will work here...)

Allows the user to specify an `invertTransparency` option. This basically cuts out the wave and puts a background color around the cutout, allowing the user to put stuff behind the wave (like regions) -- this could allow various effects, like different wave colors for different regions.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
I'm not such a fan of `invertTransparency`, it's not immediately clear from the name what this option does. Can you try and come up with a better name?

**Comment by agamemnus** [comment]
Well, it causes the transparent pixels to become solid, and vice-versa. It takes the transparency and inverts it... not sure.

**Comment by thijstriemstra** [comment]
ok but what part get's transparent (or the opposite). (invert)waveTransparency-something?

**Comment by agamemnus** [comment]
The whole canvas transparency is inverted.. invertWave is shorter but it
also inverts bars so it's not accurate, and it's not clear what invert
means here.

Umm.. What about inverseOpacity or invertOpacity?

On Jun 25, 2017 12:38 PM, "Thijs Triemstra" <notifications@github.com>
wrote:

ok but what part get's transparent (or the opposite).
(invert)waveTransparency-something?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/katspaugh/wavesurfer.js/pull/1133#issuecomment-310913272>,
or mute the thread

**Comment by agamemnus** [comment]
Thanks.... will rework with current code in the near future...

**Comment by thijstriemstra** [comment]
> Thanks.... will rework with current code in the near future...

@agamemnus  can you rebase/create a new pull request based on the current master branch?

**Pull request closed without merging**
