### PR TITLE
Add missing comments to ignore options + add W083.

### PR DESCRIPTION
**Pull request by agamemnus**
I believe W083 allows code like the following, whereas the checker would normally error out:
````
a.forEach (function (b) {
 b.forEach (function (c) {
 })
})
````

### CODE REVIEW

**Comment by agamemnus** [comment]
When running playPause, you might want to know right away whether something is playing or not, or whether the pause succeeded. I don't remember why I added this here. Maybe an accident...

**Comment by thijstriemstra** [comment]
This PR has conflicts that must be resolved.

**Comment by agamemnus** [comment]
:/

**Comment by agamemnus** [comment]
There is no longer a gruntfile....

**Comment by mspae** [comment]
Obsolete since linter changes to prettier I think. Please reopen if not.

**Pull request closed without merging**
