### PR TITLE
Corrects region width problem

### PR DESCRIPTION
**Pull request by RocAlayo**
I believe this problem was created by merging one of my last Pull Request. That or it was entirely my fault :P
Either way here is the patch :)

### CODE REVIEW

**Comment by katspaugh** [comment]
Could you roll back my last commit from your branch? It's no longer in the master.

**Comment by RocAlayo** [comment]
I can't I deleted my fork after the merge. If you want to apply the change yourself I don't mind. If I remember correctly the pull request was only two lines of code in `updateRender` of `wavesurfer.regions` file:
```javascript
var fillParentNoScroll = (!this.wavesurfer.params.scrollParent && this.wavesurfer.params.fillParent);
var width = fillParentNoScroll ? this.wavesurfer.drawer.getWidth() : this.wrapper.scrollWidth;
```
The problem is that below this lines there is the old declaration of `width`.

**Comment by katspaugh** [comment]
Merged, thanks!

**Comment by RocAlayo** [comment]
Thanks to you to for this great project!

**Pull request merged**
