### PR TITLE
Support for XHR options

### PR DESCRIPTION
**Pull request by janhartmann**
This pull request expands the `load(url)` method to support object initialisation. This means you will be able to add headers and other request specific properties to the load function.

Example:

```js
this.wavesurfer.load({
    url: '/url/to/file.wav',
    requestHeaders: [
        { 
            key: "Authorization": 
            value: "my-token"
        }
    ]
});
```

Other options within `ws.util.ajax` will also be overridable.

### Short description of changes:

- I've added the support for adding request headers on the the XHR request.
- I've handling the support for having the `url` variable both as a string and as a object.
- I've added a preload check whether the object as a minimum contains a `url` property.

### Breaking in the external API:
Should not be any.

### Breaking changes in the internal API:
Should not be any.

### Todos/Notes:
We could argue that `url` is not a suitable name for the variable anymore, since it can now be a string, object and an element. 

### Related Issues and other PRs:
Authorization headers enhancement #1038
#1100

### CODE REVIEW

**Comment by janhartmann** [comment]
Wauw, that a huge pull request. But yes, I see.

Not sure I got the time on my hands right now for looking into that. Feel free to close this merge request! :-)

**Comment by thijstriemstra** [comment]
The pull request is huge, but the actual diff is tiny..

**Comment by thijstriemstra** [comment]
@janhartmann refactored the changes and added an `xhr` parameter. Instead of passing the object to `load` use that wavesurfer option instead and supply it with an object, e.g.

```javascript
var xhr = {
    requestHeaders: [
        { 
            key: "Authorization": 
            value: "my-token"
        }
    ]
}
```

Also incorporated the `withCredentials` option from #1100.

**Comment by janhartmann** [comment]
This is perfect for our needs, thank you so much!

**Pull request merged**
