### PR TITLE
add setMute() method to docs

### PR DESCRIPTION
**Pull request by entonbiba**
add setMute() method to docs #1041

### CODE REVIEW

**Comment by tomasvilda** [comment]
setMute() has boolean parameter, so it can mute on true and unmute on false.

**Comment by thijstriemstra** [comment]
please see prev comment

**Comment by entonbiba** [comment]
@thijstriemstra updated

**Comment by thijstriemstra** [comment]
is it really called `boolean`?

**Comment by entonbiba** [comment]
@thijstriemstra updated, set it as boolean since it had true/false values ><

**Pull request merged**
