### PR TITLE
New Event: waveform-ready

### PR DESCRIPTION
**Pull request by X-Raym**
Add a 'waveform-ready' event, triggered when waveform is drawn with
MediaElement backend.

### CODE REVIEW

**Comment by X-Raym** [comment]
Initial patch : https://github.com/katspaugh/wavesurfer.js/pull/856

**Comment by katspaugh** [comment]
Cool, thanks a lot!

**Comment by X-Raym** [comment]
@katspaugh glad to participate a bit to this great project 👍

**Comment by X-Raym** [comment]
@katspaugh I think you forgot to update WaveSurfer version number in header of the Dist minified file 📦 https://github.com/katspaugh/wavesurfer.js/blob/master/dist/wavesurfer.min.js#L1
Should be 1.2.4 :)

**Comment by katspaugh** [comment]
No, it's 1.2.3.

**Comment by X-Raym** [comment]
@katspaugh hmm I put 1.2.4 in changelogs for the waveform-ready event.
1.2.3 was for the preload feature.

**Comment by katspaugh** [comment]
I thought I had updated the changelog to bundle both into 1.2.3, but apparently I forgot to save the file. [Updated](https://github.com/katspaugh/wavesurfer.js/blob/master/CHANGES.md) now.

**Pull request merged**
