### PR TITLE
Make drawPeaks not run twice if peaks are pre-loaded.

### PR DESCRIPTION
**Pull request by agamemnus**
Topic...

### CODE REVIEW

**Comment by agamemnus** [comment]
Similarly, (and I'm not sure about this one), but seekTo was firing twice if peaks were loaded. It should only fire once.

**Comment by agamemnus** [comment]
Now including other dodgy fixes to make sure that, for both `WebAudio` and MediaElement`:

1) ... audio plays once seekTo is fired and the audio has loaded.
2) ... "preload" causes the audio data to start loading (for WebAudio).

**Comment by X-Raym** [comment]
This sounds like a useful tricks. It should crease peak drawing performance a lot !

**Comment by mspae** [comment]
I believe this is obsolete. If you disagree please reopen.

**Pull request closed without merging**
