### PR TITLE
markers plugin: custom HTML elements are now centered over the marker line

### PR DESCRIPTION
**Pull request by bknower-cogito**
…vesurfer

Previously, the markerElement displayed when passed as a parameter to the add marker function was not centered over the line displayed on the wavesurfer, but now it is.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
> Previously, the markerElement displayed when passed as a parameter to the add marker function was not centered over the line displayed on the wavesurfer, but now it is.

Can you show a before/after screenshot?

**Comment by bknower** [comment]
> > Previously, the markerElement displayed when passed as a parameter to the add marker function was not centered over the line displayed on the wavesurfer, but now it is.
> 
> Can you show a before/after screenshot @bknower-cogito ? And a changelog entry is also missing.

Here's the before and after.
image

image

**Review by thijstriemstra — APPROVED** [review]
thanks!

**Comment by thijstriemstra** [comment]
@bknower there's a merge conflict in CHANGES.md, can you check it?

**Pull request merged**
