### PR TITLE
Next: Ports from master and bugfixes

### PR DESCRIPTION
**Pull request by mspae**
### Short description of changes:

* This ports hopefully all the (relevant) recent commits on the master branch to the next branch.
* nullified `this.arraybuffer` in `wavesurfer.destroy` to fix memory leak

### CODE REVIEW

**Comment by mspae** [comment]
@katspaugh @thijstriemstra @entonbiba AFAIK we could release `2.0.0-beta01` what do you say?

**Comment by entonbiba** [comment]
@mspae sounds great! haven't checked but are all the plugins available in version 2?

**Comment by thijstriemstra** [comment]
Sounds good. A branch with a release is fine, ill help test.

**Comment by entonbiba** [comment]
@mspae to celebrate st. patricks day I want to give away a few free download codes for my DJ Mixer app, maybe even throw in a couple when version 2 is released. What do you guys think is that alright? Should I create an issue?

**Comment by mspae** [comment]
@entonbiba I don't mind if you give away free download codes, but I think we should make it clear that it's a different project, otherwise people might open mixer app related issues here and vice versa.

@thijstriemstra Thanks for the support!

So there definitely are a few issues which are still open, but the library as a whole is functional. Here's an overview of the current status:

* All but the newest plugins are ported. (I think porting them will be uncomplicated)
  * The **timeline** plugin zooming performance issues of the v1 version are still there
  * The **minimap** plugin works *mostly* – There are still some issues because of `ready`/`waveform-ready` event inconcistencies (WebAudio and MediaElement backends with peaks and without) – I'm currently working on that and will open a PR to make the events more consistent (and document them) – then the minimap plugin should work properly. (overviewRegion and rendering of regions works)
  * The **spectrogram** labels PR I've ported
  * **regions**, **microphone** and **elan** plugin wasn't changed so much, they should work as before.
* Open bugs AFAIK the same as on master
  * Minimap plugin does not render complete waveform with large files https://github.com/katspaugh/wavesurfer.js/issues/994
  * Waveform display problem with timeline (see above) https://github.com/katspaugh/wavesurfer.js/issues/990
  * Bad zooming performance when using timeline plugin (see above) https://github.com/katspaugh/wavesurfer.js/issues/967
  * empty + redrawBuffer breaks player with pre-rendered peaks https://github.com/katspaugh/wavesurfer.js/issues/943
  * partialRender with zoom = broken https://github.com/katspaugh/wavesurfer.js/issues/932
* Also updating the jsdoc comments on the plugins would be a super way of providing complete documentation for all the plugin APIs. (The initialisation parameters are already documented that way but I think especially the regions plugin would benefit greatly from a complete documentation)
* Other things:
  * Responsive parameter was added
  * Minimap plugin doesn't have a mandatory `container` init param, if none is passed it is just appended, I would like to do the same for the timeline plugin.
  * A memory leak (nullifying `this.arraybuffer` on `wavesurfer.destroy()`) was fixed, this could be backported. I'm sure there are some other memory improvements that could and should be done, but for me fixing bugs are currently the 1. priority.
  * I would recommend we create a `v2` directory in the `gh-pages` branch to contain the website for v2, then we could link to it from the current v1 page (like the webpack project website: https://webpack.github.io/) – Then we could cleanly seperate marketing content and examples from the actual (generated) technical documentation. The latter will be always up-to-date since it is part of the release workflow to generate new docs and push the `gh-pages` branch.

**Pull request merged**
