### PR TITLE
Fix #1252: SplitChannels not rendering

### LINKED ISSUE #1252: splitChannels option results in no peaks being painted, 2.0.0-beta02
All of my configuration works fine until introducing `splitChannels: true` - which results in no peaks being painted.  I have reduced my configuration to simply `splitChannels: true` and experience the same thing.  I see this on Chrome 62 and Firefox 56, OSX.

It seems to be the same issue found here: https://github.com/katspaugh/wavesurfer.js/issues/942 that was fixed in 1.3.1.  I am, however, using 2.0.0-beta02 and loading the library as a module.  I am instantiating the timeline plugin as well.

I have tried with multiple audio files (.wav) that I have confirmed have two channels.

Screenshot:
screen shot 2017-11-07 at 11 34 56 am

### PR DESCRIPTION
**Pull request by mspae**
### Short description of changes:
- `Drawer.prepareDraw` was not passing peaks data that was prepared for `splitChannels` rendering to the rendering function. This PR corrects that.

### Breaking in the external API:
/

### Breaking changes in the internal API:
/

### Todos/Notes:
- Also there was some formatting (I don't know why, but it wouldn't build without :zap: )

### Related Issues and other PRs:
- Fixes #1252

### CODE REVIEW

**Comment by thijstriemstra** [comment]
since when is this a bug? just so I know what to test against.

**Comment by thijstriemstra** [comment]
Also most of this PR is not related to the issue described. Please break these things up into multiple PRs so it's possible to review them properly.

**Comment by taggartbg** [comment]
+1, I'd love to see this fixed!  Thanks @mspae and @thijstriemstra !

**Comment by thijstriemstra** [comment]
@taggartbg it's in master branch now, can you try it out?

**Pull request merged**
