### PR TITLE
drawBars and drawWave share some code... combine it + other optimization.

### PR DESCRIPTION
**Pull request by agamemnus**
drawBars and drawWave share some code on top. I refactored and then offloaded that into a new function called routeAndClear.

I also reworked/streamlined the rest of the code slightly. Will add the single canvas if OK.

Shouldn't affect anything else...

### CODE REVIEW

**Comment by agamemnus** [comment]
OK, this needs to be put on hold because the request animation frame change just really is a big change.

**Comment by thijstriemstra** [comment]
I'm also really reluctant to make these changes without any unit tests that verify it works as expected. Can you take a look at that?

**Comment by agamemnus** [comment]
I made way too many changes for now, and partialRender doesn't work... although I am not sure how well it worked before. Let's wait for the smaller changes to go through.

**Comment by mspae** [comment]
This is redundant since #1198 was merged, no? Sorry I didn't see this PR before doing the refactor, otherwise I would have reused some of the stuff. Can we close this now @agamemnus ?

**Comment by agamemnus** [comment]
My code would probably need too much work by now. I'll stick with my version, though...

**Pull request closed without merging**
