### PR TITLE
add methods setCurrentTime

### PR DESCRIPTION
**Pull request by entonbiba**
add methods
**setCurrentTime(seconds)**
sets the current time in seconds

**setCurrentTimeBetween(start,end)**
sets the current time in the middle of the set start and end seconds

#1039

### CODE REVIEW

**Comment by mspae** [comment]
Or in other words it does what `seekTo` does, Just with a percentual Value.

**Comment by entonbiba** [comment]
@mspae yes, it sets the current time between the provided start and end seconds.

**Comment by entonbiba** [comment]
@thijstriemstra done, I opened another pr for the setCurrentTimeBetween.

**Comment by mattdiamond** [comment]
I think there may have been a slight typo in the `setCurrentTime` function... just noticed it when I was browsing the code to learn more about the library. I left a comment on https://github.com/katspaugh/wavesurfer.js/commit/ffef86e7c0a78a1b736bdba9a1058abe54910ba7.

**Comment by thijstriemstra** [comment]
@mattdiamond can you open a PR for that? thanks.

**Pull request merged**
