### PR TITLE
Update bower.json

### PR DESCRIPTION
**Pull request by nishesj**

### CODE REVIEW

**Comment by nishesj** [comment]
duplicate

**Comment by nishesj** [comment]
Reopen cause the duplicate pull req #378  has wrong filename

**Comment by katspaugh** [comment]
Thanks!

Does anyone know whether `bower.json` is even necessary when there's a `package.json`?

**Comment by thijstriemstra** [comment]
Once registered its not needed.

**Comment by katspaugh** [comment]
Thanks, I'll kill it then.

**Pull request merged**
