### PR TITLE
add getFilters() method to Documentation

### PR DESCRIPTION
**Pull request by entonbiba**
merge after pull request #982 to update website docs for methods page

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Why not add to #982? From the PR names it's impossible to tell whether these 2 are different @entonbiba

**Comment by entonbiba** [comment]
@thijstriemstra it's in the gh-pages branch though? This would update the docs while the other would update the master branch.

**Comment by thijstriemstra** [comment]
oh my, sorry, you're right :man_facepalming:

**Comment by thijstriemstra** [comment]
For some reason the build [failed](https://travis-ci.org/katspaugh/wavesurfer.js/builds/200489654) so I started it again, will merge when it's green.

**Comment by thijstriemstra** [comment]
Actually, I have no idea why it's failing, any idea @entonbiba?

**Comment by entonbiba** [comment]
@thijstriemstra yea it's been failing for the gh-pages branch, it's missing the travis.yml file gh-pages it says.

**Comment by thijstriemstra** [comment]
ok so lets get a .travis.yml in there that basically does nothing (or checks that branch, I'm not familiar with the content/structure/packages used in that branch). I wouldn't mind including that change in this pull request.

**Comment by entonbiba** [comment]
something like this or purely blank?
````
language: node_js
sudo: false
````

````
````

**Comment by thijstriemstra** [comment]
I'm not sure, there's probably many others that encountered the same issue, probably a github help page for it somewhere?

**Comment by entonbiba** [comment]
@thijstriemstra I think the following will work since the error is due to the default travis config running ruby.

````
language: generic
````

**Comment by entonbiba** [comment]
@thijstriemstra ok I created the generic travis.yml and it works!

**Comment by thijstriemstra** [comment]
Sweet, thanks!

**Pull request merged**
