### PR TITLE
fix destroy wrapper issue

### LINKED ISSUE #323: Destroying before rendering is complete
When you have an audio file (let's say 4 MB) that takes a while to render (let's say 10 sec) and you `destroy` the wavesurfer instance before it completed rendering you'll see the following error:

```
TypeError: this.wrapper is null
http://localhost:8080/wavesurfer.js/src/drawer.js
Line 92
```
This example uses bootstrap to create a modal that renders the waveform and destroys the wavesurfer when closing the modal: https://gist.github.com/thijstriemstra/f1900272b8d680bda765

### PR DESCRIPTION
**Pull request by thijstriemstra**
This fixes #323 and adds some improvements to the microphone plugin.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
hi @katspaugh, could you let me know if there are any changes in here that you cant accept? Just pinging because I remember you saying you missed my last pull request.

**Comment by katspaugh** [comment]
Everything is fine, thank you!

**Comment by thijstriemstra** [comment]
Thanks! Could you make a new release as well?

**Comment by katspaugh** [comment]
Done!

**Pull request merged**
