### PR TITLE
add wavesurfer.getPlaybackRate()

### PR DESCRIPTION
**Pull request by entonbiba**
create getPlaybackRate method and return playback rate.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
But you just added a `getPlaybackRate` method to the backend right? Why not use that in this PR, I'm confused.

**Comment by entonbiba** [comment]
@thijstriemstra should I create a new pull request with both?

**Comment by thijstriemstra** [comment]
@entonbiba you can make a new pull request or add to this one.

**Comment by entonbiba** [comment]
@thijstriemstra just realized the webaudio.js change was already approved and merged. #936 
So this request is updating only the wavesurfer.js file.

**Comment by thijstriemstra** [comment]
@entonbiba I understand but why is this not using `return this.backend.getPlaybackRate();`

**Comment by entonbiba** [comment]
@thijstriemstra you're right, fixed 👍

**Pull request merged**
