### PR TITLE
regions plugin: handle position fix while using with channelIdx param

### PR DESCRIPTION
**Pull request by yesseyev**
# Short description of changes:
There was issue of region's handle positioning in render. Handle style was previously changed due to channelIdx feature implementation. Region handle styles (top, height) where changed to original values.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
what do you think about this PR @Frank3K?

**Comment by Frank3K** [comment]
@thijstriemstra I'm not sure what the issue is that is reported by @yesseyev. This PR reverts changes that (I think) are needed for d8b768c1ea3902a44a5c29ef2bc9d8b398ec3f0e / #1829.

If `channelIdx` is not used, the `top` and `height` are just as expected. See [lines 52-53](https://github.com/katspaugh/wavesurfer.js/blob/cf295db17d5726ad2522cb133b711184779c5120/src/plugin/regions.js#L52-L53) and [lines 178-181](https://github.com/katspaugh/wavesurfer.js/blob/cf295db17d5726ad2522cb133b711184779c5120/src/plugin/regions.js#L178-L181).

**Comment by yesseyev** [comment]
@Frank3K 
Problem is when you are using **channelIdx** param in _Region_, it draws regions on separate channels, however their handlers located somewhere else (not on the sides of region) and it makes impossible to resize the region. My PR solves this issue.

**Comment by Frank3K** [comment]
@yesseyev Thanks for the explanation, now I understand the issue. Since the handles are children of the region element, they indeed do not need to have the calculated top / height. The 0 px / 100% values ensure they are the same height as the region.

Good fix!

**Pull request merged**
