### PR TITLE
release: 3.1.0

### PR DESCRIPTION
**Pull request by thijstriemstra**
@katspaugh can you merge/tag/release this?

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Also update the site: https://github.com/katspaugh/wavesurfer.js/blob/gh-pages/README.md#update-website

**Comment by katspaugh** [comment]
Done! Thanks a lot!

**Comment by katspaugh** [comment]
Btw, @thijstriemstra, I can add you as a maintainer on npm if you like.

**Comment by thijstriemstra** [comment]
sounds good @katspaugh, my profile name is `collab`.

**Comment by katspaugh** [comment]
Cool, added!

**Comment by aburai** [comment]
well deserved @thijstriemstra you're doing a good job to improve the project, special thanks to you

**Comment by thijstriemstra** [comment]
thanks!

**Pull request merged**
