### PR TITLE
Feat: [Spectrogram] add gain, range and scale options

### LINKED ISSUE #1648: Logarithm scale on Y axis in Spectrogram plugin
Hi,

I was wondering if there exists an option to print canva chart of spectrogram plugin using a logarithm scale on Y axis (KHz) in wavesurfer.js 2.2.1 ?

Like this for example :

690x0w

It would really useful in certain cases !

Thank you

### PR DESCRIPTION
**Pull request by pengzhendong**
## Short description
Resolves #1648

Based on: 
- https://manual.audacityteam.org/man/spectrogram_settings.html
- https://manual.audacityteam.org/man/spectrogram_view.html

1. add options `gainDB` and `rangeDB`
  - Gain (dB): Increases / decreases the brightness of the display. For small signals where the display is mostly "blue" (dark) you can increase this value to see brighter colors and give more detail. If the display has too much "white", decrease this value. The default is 20dB and corresponds to a -20 dB signal at a particular frequency being displayed as "white".
  - Range (dB): Affects the range of signal sizes that will be displayed as colors. The default is 80 dB and means that you will not see anything for signals 80 dB below the value set for "Gain".
2. add Mel scale
3. add colormap `roseus`: https://github.com/dofuuz/roseus/blob/main/roseus/cmap/roseus.py

## Screenshots
Screenshot 2024-07-19 at 23 03 01

## Checklist
* [ ] This PR is covered by e2e tests
* [x] It introduces no breaking API changes

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
Awesome, thank you!

**Comment by pengzhendong** [comment]
@katspaugh Could you help me to fix the e2e test errors? I'm not familiar with cypress.

**Comment by katspaugh** [comment]
Strange, the images look the same. I’ll check.

**Comment by katspaugh** [comment]
On my local machine, the tests are also passing. 🤷 Anyway, merged the PR.

Thanks a lot! ❤️

**Comment by pablodz** [comment]
Awesome work, just using it

**Comment by puneet-yadav** [comment]
@pablodz Are you not having issues with height of the spectrogram? can you please provide the code.

**Comment by pablodz** [comment]
fixed with `linear` property

```

        this.ws = WaveSurfer.create({
          container: `#waveform-${this.uniqueId}`,
          waveColor: '#7F5FC0',
          progressColor: '#5A3A7E',
          mediaControls: true,
          height: 100,
          plugins: [
            Spectrogram.create({
              scale: 'linear',
              height: 100,
              labels: true,
              container: `#spectrogram-${this.uniqueId}`,
            }),
          ],
        });
```

**Pull request merged**
