### PR TITLE
spectrogram plugin: fix event listeners

### LINKED ISSUE #1585: spectrogram issue
ws.on('redraw', this.render); in spectrogram.js   391 line 。 this.render.bind(this);

### PR DESCRIPTION
**Pull request by thijstriemstra**
fixes #1585

### CODE REVIEW

**Comment by zhang19940101** [comment]
In that case，this.wavesurfer.un('redraw', this.render);  in spectrogram.js 338 line,
this.render.bind(this)  and this.render not  the same function.
What about this one?

**Comment by thijstriemstra** [comment]
hm, what about adding a `this._onRender = () => this.render();` and use `this._onRender` for add/remove listener?

**Comment by zhang19940101** [comment]
ok

**Comment by thijstriemstra** [comment]
@zhang19940101 feel free to open a new PR, I guess the `_wrapperClickHandler` needs a similar treatment. Bah javascript.

**Comment by zhang19940101** [comment]
ok

**Pull request merged**
