### PR TITLE
release 4.1.0

### PR DESCRIPTION
**Pull request by thijstriemstra**
@katspaugh can you merge/tag/publish this?

### CODE REVIEW

**Comment by katspaugh** [comment]
Karma is timing out, I guess I can ignore that?

**Comment by katspaugh** [comment]
Done & done 👍

**Comment by sundayz** [comment]
npm release?

**Comment by thijstriemstra** [comment]
yea, can you take a look @katspaugh?

**Comment by katspaugh** [comment]
It's published, NPM is probably lagging.

**Comment by thijstriemstra** [comment]
There now. "4.1.0 • Public • Published 14 minutes ago"

> NPM is probably lagging.

Weird.

**Comment by katspaugh** [comment]
The first time I published yesterday must have failed then.

**Comment by thijstriemstra** [comment]
It also appears the github action for the latest release didn't work, it's still on 4.0.1 on main github page.

**Comment by katspaugh** [comment]
I've hidden the Release and Package sections from the github page.

**Pull request merged**
