### PR TITLE
markers plugin: check for event after every add/remove

### LINKED ISSUE #2560: markers plugin: draggable feature only works if there is at least one marker in the initial markers list
### Wavesurfer.js version(s):

6.2.0

### Browser and operating system version(s):

Chrome on macOS

### Code needed to reproduce the issue:

```javascript
const ws = WaveSurfer.create({
		container: container,
		plugins: [
			MarkersPlugin.create({
				markers: [],
			}),
	});
	ws.load(url);
	ws.addMarker({
		time: 0.2,
		label: "V1",
		color: "#ff990a",
		draggable: true,
	});
	ws.addMarker({
		time: 1.0,
		label: "V2",
		color: "#00ffcc",
		draggable: true,
	});
```

### Use behaviour needed to reproduce the issue:

Try to drag one of the markers. It won't work. However, if at least one marker is in the initial markers list, it will work.

### PR DESCRIPTION
**Pull request by rstefek**
### Short description of changes:
Fixing of issue, added listeners check after add

### Breaking in the external API:
N/A

### Breaking changes in the internal API:
N/A

### Todos/Notes:
Not fully tested

### Related Issues and other PRs:
fixes #2560

### CODE REVIEW

**Comment by thijstriemstra** [comment]
> Not fully tested

What is the plan for this PR @rstefek?

**Comment by rstefek** [comment]
> > Not fully tested
> 
> What is the plan for this PR @rstefek?

I will prepare local development environment for the plugin and provide results.

**Comment by rstefek** [comment]
Hello,
functionality tested on local environment.
1) Marker is draggable after adding later than in initialization
2) Events are called correctly just once even if more draggable markers are added (fix to original code was needed)

**Comment by rstefek** [comment]
Hi,
added entry for version 6.4.0 (unreleased)

**Pull request merged**
