### PR TITLE
docs: add test cases for abort and destroy

### PR DESCRIPTION
**Pull request by wfk007**
## Short description
add two test cases for abort, refer to: https://github.com/katspaugh/wavesurfer.js/pull/3641#issuecomment-2041978173

## Implementation details
case1: destroy before wavesurfer ready should emit AbortError Exception, it is for https://github.com/katspaugh/wavesurfer.js/pull/3614
case2: load url after destroyed should not emit AbortError Exception, it is for https://github.com/katspaugh/wavesurfer.js/issues/3637

## How to test it
yarn run cypress

## Screenshots
image

## Checklist
* [x] This PR is covered by e2e tests
* [x] It introduces no breaking API changes

### CODE REVIEW

**Review by katspaugh — APPROVED** [review]
Awesome, thank you!

**Comment by wfk007** [comment]
I'm weird why the e2e works locally but keeps failing in GitHub jobs
image

**Comment by katspaugh** [comment]
Indeed, that's weird. I'll try on my machine locally.

**Comment by katspaugh** [comment]
Fixed it :)

**Pull request merged**
