### PR TITLE
Join ends of peaks

### PR DESCRIPTION
**Pull request by agamemnus**
I'm not entirely sure that the peaks are joined at the ends. When I zoomed all the way in, it seemed that there were gaps...

### CODE REVIEW

**Comment by agamemnus** [comment]
Actually, should be +1 for all. But I'm just guessing here. Not even sure about `var length = peaks.length / 2;`...

**Comment by thijstriemstra** [comment]
> When I zoomed all the way in, it seemed that there were gaps...

Can you provide a screenshot?

**Comment by agamemnus** [comment]
difference

**Comment by katspaugh** [comment]
Merged, thanks!

**Pull request merged**
