### PR TITLE
add RTL option

### LINKED ISSUE #1296: Right to Left Support
Thanks for the Great work.
in my project, I need the wave to be right-to-left.
is there any simple way to achieve this?
Does replacing all `right` and `left` in the project do the job?

### LINKED ISSUE #1319: form with direction RTL have render issues with TimeLine + Zoom and other
### Wavesurfer.js version(s): 
v2.01

### Browser version(s):
Chrome 64.0.3282.140 , Firefox quantum 58.0.1

### Code needed to reproduce the issue:
Add dir="RTL" on your form and test seek, play ..
I do it on this code  : [https://github.com/katspaugh/wavesurfer.js/issues/new](url)
`<div **dir="RTL"**><div id="waveform"></div>
<div id="waveform-timeline"></div>
</div> ....`

Workarround for me => always put dir="LTR" in wave div !
In this case wavesurfer is alway LTR for all.

### PR DESCRIPTION
**Pull request by samanmohamadi**
fixes #1296 
fixes #1319 
closes #1331 

it isn't tested with plugins.

### CODE REVIEW

**Comment by samanmohamadi** [comment]
Yes, ASP

**Comment by thijstriemstra** [comment]
any news @samanmohamadi?

**Comment by samanmohamadi** [comment]
Sorry about the delay but I try to complete this next weekend.

**Comment by Aparus** [comment]
And how to activate this feature? I can't find it in docs. I tried this way but it doesn't work: 
```
    const wavesurfer = WaveSurfer.create({
      container: this.waveform,
      scrollParent: true,
      minPxPerSec: 200,
      rtl: true,


    });
```

**Comment by Aparus** [comment]
> Sorry about the delay but I try to complete this next weekend.

Hi! @samanmohamadi , can I help you with docs or test? I need this feature :-)

**Comment by samanmohamadi** [comment]
@Aparus  absolutely.
thank you

**Comment by Aparus** [comment]
@samanmohamadi , how? give me instructions.

**Comment by samanmohamadi** [comment]
> @samanmohamadi , how? give me instructions.
I have added the RTL example, I think if you write the test it could be merge.
honestly, I have no idea how to do that because there isn't any test related to the mouse event to get inspiration.

**Comment by thijstriemstra** [comment]
@samanmohamadi please also remove the `dist/` files from this PR, they shouldn't be part of the repository (like I mentioned before).

**Comment by thijstriemstra** [comment]
> honestly, I have no idea how to do that because there isn't any test related to the mouse event to get inspiration.

I'll take a look.

**Pull request merged**
