### PR TITLE
cursor plugin: fix element removal in destroy

### LINKED ISSUE #2460: [cursor] Node.removeChild: Argument 1 does not implement interface Node.
Since upgrading to Wavesurfer.js, our Sentry is catching the following exceptions when our app calls `wavesurfer.destroy()`:

```
TypeError: Node.removeChild: Argument 1 does not implement interface Node.
  at destroy(./node_modules/wavesurfer.js/dist/plugin/wavesurfer.cursor.js:250:30)
  at destroyPlugin(./node_modules/wavesurfer.js/dist/wavesurfer.js:4316:18)
  at forEach(./node_modules/wavesurfer.js/dist/wavesurfer.js:4334:23)
  at destroyAllPlugins(./node_modules/wavesurfer.js/dist/wavesurfer.js:4333:47)
  at destroy(./node_modules/wavesurfer.js/dist/wavesurfer.js:5541:12)
```

and

```
TypeError: this.cursor is null
  at destroy(./node_modules/wavesurfer.js/dist/plugin/wavesurfer.cursor.js:250:7)
  at destroyPlugin(./node_modules/wavesurfer.js/dist/wavesurfer.js:4316:18)
  at forEach(./node_modules/wavesurfer.js/dist/wavesurfer.js:4334:23)
  at destroyAllPlugins(./node_modules/wavesurfer.js/dist/wavesurfer.js:4333:47)
  at destroy(./node_modules/wavesurfer.js/dist/wavesurfer.js:5541:12)
```

👇 
https://github.com/katspaugh/wavesurfer.js/blob/46d423b882d503cafd4d2498a230ff20ce39fe19/src/plugin/cursor/index.js#L242

```
TypeError: can't access property "getBoundingClientRect", o.displayTime is null
  at apply(./node_modules/wavesurfer.js/dist/plugin/wavesurfer.cursor.js:122:18)
  at o(./node_modules/@sentry/browser/esm/helpers.js:73:23)
```

👇 
https://github.com/katspaugh/wavesurfer.js/blob/bff81af86e581412ed2b506b9fbeb706b605d663/src/plugin/cursor/index.js#L93

### PR DESCRIPTION
**Pull request by JanMisker**
When the plugin `destroy(`) method get called, I got an error because `removeChild()` was called with something that wasn't a `Node`, for `this.showTime` and `this.cursor`. 

### Short description of changes:
It seems that `showTime` and `cursor` are `Proxy` objects, and the `removeChild()` doesn't swallow that. Changing from e.g. `removeChild(this.cursor)` to `this.cursor.remove()` on the Proxy objects seems to fix this.

### Breaking in the external API:
n/a

### Breaking changes in the internal API:
n/a

### Todos/Notes:
n/a

### Related Issues and other PRs:

fixes #2460

### CODE REVIEW

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks @JanMisker Can you also add a changelog entry (for new 6.0.3) with a reference to #2460?

**Comment by JanMisker** [comment]
Check, added an entry in the changelog.

**Comment by thijstriemstra** [comment]
now there's a merge conflict, probably in changelog

**Comment by JanMisker** [comment]
I can't really resolve that change I think, but adjusted CHANGES.md to be just the addition of 'my line'.

**Review by thijstriemstra — APPROVED** [review]
thanks.

**Comment by caugner** [comment]
Thanks @JanMisker, much appreciated!

**Pull request merged**
