### PR TITLE
Fix annotations example

### PR DESCRIPTION
**Pull request by osheroff**
Hi guys.  Went to see if annotations was the solution to my problem. 

It's not, but this fixes the public facing example.

### CODE REVIEW

**Comment by osheroff** [comment]
this also fixes the regions plugin example.

**Comment by thijstriemstra** [comment]
> It's not, but this fixes the public facing example.

What was specifically the issue? The build for this PR is now failing.

**Comment by osheroff** [comment]
> What was specifically the issue?

check out the examples for region and annotations (and anything that includes trivia.js); they're failing under chrome with "wavesurfer" is already defined.

> The build for this PR is now failing.

yeah, seems unlikely that this PR caused it but I'll see.

**Comment by osheroff** [comment]
https://github.com/babel/babel-eslint/issues/487 is the same issue; class field declarations are throing a no-undef from eslint.

I've spent 10 minutes now and that's my yak shaving budget for the day.  Yours if you want it :)

**Comment by thijstriemstra** [comment]
fixed in #2196

**Pull request closed without merging**
