### PR TITLE
Fixes inconsistent events with backend when playing ranges/regions

### PR DESCRIPTION
**Pull request by kjantzer**
Addresses #398 and #471: backend player not fires events for play and pause and wavesurfer forwards these events on; region now properly fires it's `out` event

### CODE REVIEW

**Comment by katspaugh** [comment]
Sorry, `Math.round(time*100)/100 ` isn't a good solution. It will make other cases fail.

**Comment by kjantzer** [comment]
@katspaugh – Which cases?

**Comment by katspaugh** [comment]
Cases where precision matters.

Besides, I don't get why in your case it wasn't firing. The original code was like this:

`if (!my.firedOut && my.firedIn && my.end <= time) {`

So if `audioprocess` gives you `19.9999` at some point, and your end mark is `20`, `region-out` would still be fired in the next frame (when the time would be, say, 20.00000001`), wouldn't it?

The rest of the PR (moving `play`, `pause` and `finished` events to the audio backends) was good, I'd merge these changes if you would be kind enough to make a separate PR (don't include the build, I'll update the version and rebuild anyway).

**Comment by kjantzer** [comment]
@katspaugh - that was the problem, the time stopped at 19.999 and never reached 20.000001. I tested regions in the very beginning and at the end and neither fired.

From my testing, `Math.round(time*100)/100` is still quite accurate. For example:

`19.994` = `19.99`
`19.995` = `20`

So **at most five-thousandths (.005) of a second is lost**. I can't imagine how this would be a problem when the function is just calling `out` events:

```
my.fireEvent('out');
my.wavesurfer.fireEvent('region-out', my);
```

To me, this would be better than not having the events fire at all, but its your call.

If you still don't think the round is a good thing, I can make another PR without that part.

**Comment by katspaugh** [comment]
I may be wrong. Let's push it.

**Comment by katspaugh** [comment]
@kjantzer I've merged your patch manually, thanks!

**Pull request closed without merging**
