### PR TITLE
fix render waveform

### PR DESCRIPTION
**Pull request by entonbiba**
fixes render waveform with peaks.
#1067 #1055

preview: https://codepen.io/entonbiba/pen/PmpXqJ

waveform-error

to

waveform-test

### CODE REVIEW

**Comment by agamemnus** [comment]
I don't think `width*end` is correct. I am getting tiny spikes at intermittent periods now.

**Comment by agamemnus** [comment]
In fact, shouldn't it be `end = width  + 1`?

**Comment by X-Raym** [comment]
@taylorvc can you confirm the  `end = width - 1` suggestion by @agamemnus works for you with long audio files ? :)

**Comment by agamemnus** [comment]
@X-Raym: Don't you mean @entonbiba?..

**Comment by taylorvc** [comment]
@X-Raym changing to `end = width -1` does not solve the issue for small or large files. Here is the waveform for a 4.5 hour long file:
image

Here is the waveform for a 20 min file:
image

**Comment by X-Raym** [comment]
@taylorvc Thanks for testing :)
I think it is better to stay with the @entonbiba fix then 👍

**Comment by agamemnus** [comment]
Oh, the spikes problem seemed to coincide with a formatting error (which is now fixed), so probably nothing -- I have been using PHP to output audio files based on a request to the server.

**Comment by X-Raym** [comment]
@agamemnus good ! So, I think this PR is ready to be merge in its current state ? Or is there any problem left ?

**Comment by agamemnus** [comment]
I'm just not sure why it is 9999. Seems arbitrary. I would like to try to figure out the root cause...

**Comment by X-Raym** [comment]
@agamemnus 9999 was arbitrary, but now it is `end = width*end;` (it may seems also arbitrary, but surely more flexible than an absolute value). But finding the cause of the problem may be better indeed. Good luck in your investigation ! :)

**Comment by entonbiba** [comment]
@X-Raym @agamemnus @taylorvc Is the spike thing happening on a specific browser? Not able to replicate it on my end.

**Comment by agamemnus** [comment]
Not an issue anymore. Just a malformed file.

**Comment by entonbiba** [comment]
@agamemnus sounds good

**Comment by agamemnus** [comment]
Here is the problem: getPeaks uses sub-ranges and not width.

The correct could would then be:
````
            var numberOfChannels = this.backend.buffer ? this.backend.buffer.numberOfChannels :
                this.backend.preload ? this.backend.preload.numberOfChannels : 2;
            var subrangeLength = this.backend.peaks ? this.backend.peaks.length / numberOfChannels: width;
            start = 0;
            end = subrangeLength - 1;
            var peaks = this.backend.getPeaks(subrangeLength, start, end);
            this.drawer.drawPeaks(peaks, width, start, end);
````

Other issues/notes:
1) This adds a new parameter that we should pull from somewhere: `this.preload`, with a property of `numberOfChannels`.
2) I am not sure if the fireEvent should fire width or subrangeLength.
3) I suggest also that we rename getPeaks's `length` parameter into `subrangeLength` to differentiate the two.

**Comment by agamemnus** [comment]
Updated code above.

**Comment by agamemnus** [comment]
@entonbiba: updated code above.... thoughts?

**Comment by X-Raym** [comment]
@entonbiba Hi ! any news about this bug ?

**Comment by entonbiba** [comment]
@agamemnus @X-Raym I like the subrangeLength idea. The current quick fix `end = width*end;` should be merged first to at least fix the current issue of no waveform showing. We should open another pr for the subrange length as it would need more testing with larger and smaller file sizes.

I've been looking into `createPeriodicWave` webaudio method as well which looks interesting.

**Comment by agamemnus** [comment]
It definitely hairy though.

**Comment by X-Raym** [comment]
@entonbiba has this been fixed ?

**Comment by entonbiba** [comment]
@X-Raym I opened another pr since this one had too many already merged prs.

**Comment by X-Raym** [comment]
@entonbiba ok thx !

**Pull request closed without merging**
