### PR TITLE
update js cdn link to 1.3.5

### PR DESCRIPTION
**Pull request by entonbiba**
updated to
//cdnjs.cloudflare.com/ajax/libs/wavesurfer.js/1.3.5/wavesurfer.min.js

### CODE REVIEW

**Comment by thijstriemstra** [comment]
are there more cdn links that need to updated in the docs @entonbiba?

**Comment by entonbiba** [comment]
@thijstriemstra I only found two references.

**Comment by thijstriemstra** [comment]
I suppose this is blocked till the file's actually online?

**Comment by entonbiba** [comment]
@thijstriemstra yes

**Comment by thijstriemstra** [comment]
I think 1.3.7 is the latest now.

**Comment by entonbiba** [comment]
@thijstriemstra updated

**Pull request merged**
