### PR TITLE
regions plugin: adjustable zIndex

### PR DESCRIPTION
**Pull request by HuangZhongtao2020**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
thanks @HuangZhongtao2020. can you make a parameter for this instead and add some documentation?

**Comment by thijstriemstra** [comment]
ping @HuangZhongtao2020

**Comment by thijstriemstra** [comment]
No response, closing. Please re-open after making requested changes.

**Comment by sundayz** [comment]
If anyone needs this, you can write CSS to set the z-index of the region element, using a selector like:

```css

wave > region {
    z-index: 123;
}

**Pull request closed without merging**
