### PR TITLE
Dev flexibility

### PR DESCRIPTION
**Pull request by Stoyvo**
### Short description of changes:
dotenv - Allow customizing build output directory, useful for larger applications that utilize this library
watch - Watch the src directory for changes, trigger the specific build command
build:main:plugins - Build library without htmlinit, for applications not using it

### Breaking in the external API:
N/A

### Breaking changes in the internal API:
N/A

### Todos/Notes:
N/A

### Related Issues and other PRs:
N/A

### CODE REVIEW

**Comment by Stoyvo** [comment]
> I'd rather not use dotenv and keep things simple. Instead of specifying `dist` with dotenv, why not move it to the `common` build file and define `dist` there so it can be reused.

The goal is to simply have a "configuration" where the library provides a default, but changes to this config are untracked in git. Other than a defined configuration file in the root, no other ideas came to mind.

> webpack-dev-server already watches and rebuilds files. Why not improve that instead of adding additional commands in npm?
I'll take a look into utilizing this a bit more. Was trying to avoid the unnecessary open port. I can remove the dependancy of `watch` and implement https://webpack.js.org/configuration/watch#watch

**Comment by thijstriemstra** [comment]
> I'll take a look into utilizing this a bit more. Was trying to avoid the unnecessary open port. I can remove the dependancy of watch and implement https://webpack.js.org/configuration/watch#watch

Sounds good.

**Comment by thijstriemstra** [comment]
ping @Stoyvo

**Comment by Stoyvo** [comment]
@thijstriemstra haven't forgotten, just overwhelmed at the moment. Will have an update hopefully this week or weekend

**Comment by thijstriemstra** [comment]
thanks for the update. we want to release 3.0 soon (#1651) and would be nice to get this in there as well.

**Comment by thijstriemstra** [comment]
it's now 2 months later and no update, so closing this. Please re-open with changes or open a new PR.

**Pull request closed without merging**
