### PR TITLE
Release 2.1.2

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@katspaugh can you merge/tag/release this? Don't forget to run this in gh-pages branch afterwards (and commit/push it): https://github.com/katspaugh/wavesurfer.js/blob/gh-pages/README.md#update-examples

**Comment by thijstriemstra** [comment]
ping @katspaugh

**Comment by Vaberer** [comment]
Hey @katspaugh , is it possible to accept this release including #1543 fix? Last release was in November 19 and our engineers are waiting for this change.

Many thanks!

Best, Patrik

**Comment by katspaugh** [comment]
Published and updated the gh-pages 👌 
Thanks, @thijstriemstra!

**Pull request merged**
