### PR TITLE
set isMuted to false on load method

### PR DESCRIPTION
**Pull request by entonbiba**
set isMuted to false on new load

#1040

### CODE REVIEW

**Comment by entonbiba** [comment]
@katspaugh should I add this as an option to allow muting to continue even after loading new audio?

**Comment by tomasvilda** [comment]
That would logical too. If I mute wavesurfer object maybe I want it to be muted on new tracks too, until I unmute.

**Comment by katspaugh** [comment]
Sure, let's add it. To me, it seems more logical to actually keep the next tracks muted by default since it's the same instance of the wavesurfer. But it's subjective.

**Comment by katspaugh** [comment]
Merged, thanks!

**Pull request merged**
