### PR TITLE
781 MultiCanvas Renderer and Zoom - Current Indicator place is changing

### PR DESCRIPTION
**Pull request by chrisparton1991**
This PR is a replacement for #785, which caused other issues. The PR pertains to #781.

Instead of dividing the waveform up into equal sizes as I tried in #785, I keep my current apportioning algorithm the same. What changes is that I record a `start` and `end` value against each canvas entry. These values are decimals between 0 and 1, and they represent the location within the waveform.

This allows me to render the correct peak data against each canvas, whereas I previously just divided the peaks evenly amongst the canvases. This was wrong because the last canvas can be much smaller than the other canvases, which screws things up.

Attached is another runnable test with the new fix: [fix-test-2.zip](https://github.com/katspaugh/wavesurfer.js/files/408957/fix-test-2.zip). Could @samih-dev, @moyara and possibly @jeremylach take a look at the new zip file and see if it solves your issues? I hope it does, I'm looking forward to this issue being closed ;)

### CODE REVIEW

**Comment by jeremylach** [comment]
I took a look at this test, though I never experienced the issue which this is supposed to fix, the test seems to work as I'd expect.  Zooming, moving the playhead around, everything plays and stays in sync.

**Comment by moyara** [comment]
Thanks @chrisparton1991 It's working fine! Awesome!

**Comment by chrisparton1991** [comment]
Thanks for the feedback, it's a relief to hear that it's working for you both!

**Comment by chrisparton1991** [comment]
I'd like @samih-dev to take a look at this, but if he doesn't respond in a day or so, feel free to review @katspaugh (and anyone else who's interested).

Do you know if this PR fixes #778, @jeremylach?

**Comment by jeremylach** [comment]
@chrisparton1991  this does not seem to fix #778 unfortunately.

**Comment by chrisparton1991** [comment]
I think we can just go ahead and review this @katspaugh.

**Comment by katspaugh** [comment]
Merged, thanks a lot!

**Pull request merged**
