### PR TITLE
small refactor, removed unnecessary re-calculation

### PR DESCRIPTION
**Pull request by jsphweid**
I noticed the calculation from progress to pos in updateProgress was already done in drawer's progress function, which I believe is the only place where updateProgress is called.

### CODE REVIEW

**Comment by katspaugh** [comment]
Good catch, thanks!

**Comment by katspaugh** [comment]
Did you test with different `pixelRatio`s and with and without the `scrollParent` option?

**Comment by jsphweid** [comment]
I just checked those on another computer (non-retina) and everything works as expected.

Although I must say I didn't touch in drawer.js under the comment `/* Renderer-specific methods */` the line `updateProgress: function (position) {}` Honestly I didn't know what that was doing and hence didn't change it >.< Not sure if it matters.

**Comment by katspaugh** [comment]
It doesn't do anything, just a placeholder for "subclasses" to override.

**Comment by chrisparton1991** [comment]
:+1: Can this be merged, @katspaugh?

**Comment by katspaugh** [comment]
Sorry, I haven't reviewed it in detail it. I'll get to it ASAP.

**Comment by katspaugh** [comment]
Thanks!

**Pull request merged**
