### PR TITLE
seekTo bugfix inc. basic unit tests

### LINKED ISSUE #1816: Error calling wavesurfer.seekTo, parameter must be a number between 0 and 1
Hi!

Thank you for your work :)

### Wavesurfer.js version: 
3.2.0 

### Browser and operating system version(s):
LinuxMint, Opera 65.0, Firefox70.0.1

### Code needed to reproduce the issue:

```javascript
var wavesurfer = WaveSurfer.create({
    container: '#player-wrap-'+u.data.id,
    waveColor: '#94919C',
    progressColor: '#007DFF',
    height: 50,
    pixelRatio: 1,
    cursorColor: '#fff',
    normalize: true,
    responsive: true
});
// blob in webm format
// and checked with wavesurfer.load('audio.wav');
wavesurfer.loadBlob(u.data.blob);
wavesurfer.on('ready', function () {
    wavesurfer.play();
});
// audioprocess event returns correct data
// wavesurfer.on('audioprocess', updateTimer);
```

### Result if seek

Выделение_140

### PR DESCRIPTION
**Pull request by Dexmaster**
### Short description of changes:
seekTo fix for issue #1816, with basic unitTests

### Related Issues and other PRs:

fixes #1816

### CODE REVIEW

**Comment by Dexmaster** [comment]
Sure @thijstriemstra, done!

**Comment by thijstriemstra** [comment]
oh can you add some separate test(s) for clamp?

**Comment by Dexmaster** [comment]
also done! :)

**Review by thijstriemstra — APPROVED** [review]
thanks.

**Comment by thijstriemstra** [comment]
Tests seem to be failing on my local machine (ubuntu 20):

```
25 08 2020 11:02:27.749:ERROR [Firefox 79.0 (Ubuntu 0.0.0) | Drawer | handleEvent should return 0.5 if clicked in the middle of wrapper]: Expected 0.5001594993676485 to be close to 0.5, 4.
<Jasmine>
./spec/drawer.spec.js/</<@http://localhost:9876/base/spec/drawer.spec.js?fac081a99de00ac23399977ddc7df464b96912aa:232:15
Firefox 79.0 (Ubuntu 0.0.0) Drawer handleEvent should return 0.5 if clicked in the middle of wrapper FAILED
	Expected 0.5001594993676485 to be close to 0.5, 4.
	<Jasmine>
	./spec/drawer.spec.js/</<@spec/drawer.spec.js:232:15
	<Jasmine>
Firefox 79.0 (Ubuntu 0.0.0): Executed 27 of 119 (1 FAILED) (0 secs / 1.261 secs)
25 08 2020 11:02:27.752:INFO [Firefox 79.0 (Ubuntu 0.0.0) | Drawer | handleEvent should not return 0 if clicked on wrappeFirefox 79.0 (Ubuntu 0.0.0): Executed 28 of 119 (1 FAILED) (0 secs / 1.262 secs)
25 08 2020 11:02:27.754:ERROR [Firefox 79.0 (Ubuntu 0.0.0) | Drawer | handleEvent should return 0.9 if clicked 10% from the end]: Expected 0.9002870988617674 to be close to 0.9, 4.
<Jasmine>
./spec/drawer.spec.js/</<@http://localhost:9876/base/spec/drawer.spec.js?fac081a99de00ac23399977ddc7df464b96912aa:243:15
Firefox 79.0 (Ubuntu 0.0.0) Drawer handleEvent should return 0.9 if clicked 10% from the end FAILED
	Expected 0.9002870988617674 to be close to 0.9, 4.
	<Jasmine>
	./spec/drawer.spec.js/</<@spec/drawer.spec.js:243:15
	<Jasmine>
```

**Comment by thijstriemstra** [comment]
>Tests seem to be failing on my local machine (ubuntu 20): 

Those particular tests should be fixed now.

**Comment by sundayz** [comment]
`.toBeCloseTo(0.5, 3)` wouldve worked because then it wouldve checked 0.5 == 0.500 instead of 0.5 == 0.5001

**Comment by thijstriemstra** [comment]
yea true, i was lazy. feel free to fix it ;)

**Comment by kubk** [comment]
Thanks for the fix. Is it gonna be published?

**Pull request merged**
