### PR TITLE
Split channels: overlay param now properly displays a single canvas

### PR DESCRIPTION
**Pull request by johnpaulmedina**
#2161 

When setting overlay: true on split channels the height of the waveform becomes equal to a single channel height but does not overlay the second channel. 

The issue is that the offsetY value is set based on height multiplied by the drawIndex or default to zero. In this case we should check for the splitChannelOptions.overlay and set the offsetY to zero regardless of the drawIndex.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
Thanks! I am slightly frustrated that the split channel option is adding all these 'workarounds' and conditionals to MultiCanvas, and cluttering the API. This is not an issue to solve in this PR but something to think about..

So, I'll let others review this PR first.

**Comment by johnpaulmedina** [comment]
@thijstriemstra I see what you mean. It sure did feel like a work around when adding the conditional statement. However, I was doing it based on previous conditionals within the prepareDraw method.

Just for thought. It looks like the split channel interacts with:

filteredChannels
overallAbsMax
offsetY

What if there are separate methods to that specifically handle these logics based on the option params? Doing so would allow for the prepareDraw method to be less conditional, keeping each action contained within it’s own method but still handling the correct output based on option params.

So having a class for channels and then each channel can have its own prototype inheritance

channel.isFiltered()
channel.getOverallAbsMax()
channel.getOffsetY()

Additionally, splitChannelOptions feels unnecessary in my opinion.

*splitChannels* could be a Boolean || String = ‘overlay’
*filteredChannels* should work at the higher param option level altogether because correct me if I am wrong here - but I don’t believe it supports nested channels?
*channelColors* could work from the higher param option waveColor and progressColor respectively. So those params should be either a String or Array where their index position corresponds to a channelIndex.
*relativeNormalization* also seems redundant since at least in my initial first thought because either we normalize or we don’t. 

These are subjective opinions since I am new to wavesurfer and audio handling altogether but might help clean up options and the MultiCanvas API as you pointed out.

**Comment by thijstriemstra** [comment]
Thanks for the feedback. What about adding an additional subclass of `MultiCanvas` where all SplitChannel stuff happens, e.g. `SplitChannelMultiCanvas` or someting like that. All your suggestions could be implemented there.

**Comment by sundayz** [comment]
@thijstriemstra I'm trying to test this but when i run `npm run start:plugins` I get an error, is this caused by #2093 or is it just me?

```
> wavesurfer.js@4.4.0 build:htmlinit F:\dev\wavesurfer.js
> webpack --config ./build-config/webpack.prod.htmlinit.js

asset wavesurfer-html-init.js 13.3 KiB [compared for emit] (name: html-init) 1 related asset
./src/html-init.js 9.41 KiB [built] [code generated]
./node_modules/load-script/index.js 1.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 2981 ms
[webpack-cli] Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property 'publicPath'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddle
ware?, onListening?, open?, openPage?, overlay?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transportMode?, useLocalIp? }
```

**Comment by thijstriemstra** [comment]
You're using `webpack 5.17.0 compiled successfully in 2981 ms` but package.json states webpack 5.13.0. Can you use the deps as specified by wavesurfer.js instead?

**Comment by sundayz** [comment]
I wiped node_modules and installed everything again and it gave me 5.17 again. I'll try again later...

The PR is 1 line so I trust that if John says it works then it works 😃

**Review by sundayz — APPROVED** [review]

**Comment by thijstriemstra** [comment]
I just updated to 5.17.0 and everything looks okay here.

```
asset wavesurfer-html-init.js 13.3 KiB [compared for emit] (name: html-init) 1 related asset
./src/html-init.js 9.34 KiB [built] [code generated]
./node_modules/load-script/index.js 1.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 1183 ms
<i> [webpack-dev-server] Project is running at http://[::]:8080/
<i> [webpack-dev-server] Content not from webpack is served from /home/thijs/projects/wavesurfer.js
<i> [webpack-dev-middleware] asset wavesurfer.js 1.09 MiB [emitted] [big] (name: wavesurfer)
<i> runtime modules 24.1 KiB 10 modules
<i> cacheable modules 381 KiB
<i>   modules by path ./node_modules/ 195 KiB
<i>     modules by path ./node_modules/webpack-dev-server/client/ 71 KiB 12 modules
<i>     modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
<i>     modules by path ./node_modules/html-entities/lib/*.js 57.9 KiB 4 modules
<i>     modules by path ./node_modules/url/ 37.4 KiB 3 modules
<i>     modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
<i>     ./node_modules/ansi-html/index.js 4.16 KiB [built] [code generated]
<i>     ./node_modules/events/events.js 13.8 KiB [built] [code generated]
<i>     ./node_modules/debounce/index.js 1.8 KiB [built] [code generated]
<i>   modules by path ./src/ 187 KiB
<i>     modules by path ./src/util/*.js 20.2 KiB 12 modules
<i>     modules by path ./src/*.js 166 KiB 8 modules
<i> ./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
<i> webpack 5.17.0 compiled successfully in 3691 ms
<i> [webpack-dev-middleware] Compiled successfully.
```

**Comment by johnpaulmedina** [comment]
I think the issue with the subclass just for split channels might be too much because it would need to be instantiated from the original prepareDraw of multicanvas ? 

I would vote to favor a ChannelClass where it has its own logic that can clean up the original prepareDraw. 

Keeping channel conditionals and logic specifically with a channel. 

I’ll take a look a little deeper later, I was just throwing out some ideas arbitrarily without looking at the entire code base

**Comment by thijstriemstra** [comment]
> instantiated from the original prepareDraw of multicanvas ?

Haven't looked into specifics yet.

> I would vote to favor a ChannelClass where it has its own logic that can clean up the original prepareDraw.

Can you elaborate, maybe some pseudo-code example?

**Comment by johnpaulmedina** [comment]
@sundayz It's a powerful one line :) LOL. Here is a build report specifically from katspaugh/wavesurfer.js pull/2167
```
From github.com:katspaugh/wavesurfer.js
 * [new ref]         refs/pull/2167/head -> split-channels-bug
❯ git checkout split-channels-bug
Switched to branch 'split-channels-bug'
❯ npm install

> wavesurfer.js@4.4.0 prepare katspaugh-wavesurfer.js
> npm run build


> wavesurfer.js@4.4.0 build katspaugh-wavesurfer.js
> npm run build:normal && npm run build:minified


> wavesurfer.js@4.4.0 build:normal katspaugh-wavesurfer.js
> npm run build:main && npm run build:plugins && npm run build:htmlinit


> wavesurfer.js@4.4.0 build:main katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.main.js

asset wavesurfer.js 196 KiB [emitted] (name: wavesurfer) 1 related asset
modules by path ./src/util/*.js 20.2 KiB 12 modules
modules by path ./src/*.js 167 KiB
  ./src/wavesurfer.js 60.2 KiB [built] [code generated]
  ./src/drawer.multicanvas.js 23 KiB [built] [code generated]
  ./src/webaudio.js 26.4 KiB [built] [code generated]
  ./src/mediaelement.js 17.7 KiB [built] [code generated]
  ./src/peakcache.js 4.89 KiB [built] [code generated]
  ./src/mediaelement-webaudio.js 6.61 KiB [built] [code generated]
  ./src/drawer.js 15.7 KiB [built] [code generated]
  ./src/drawer.canvasentry.js 11.9 KiB [built] [code generated]
./node_modules/debounce/index.js 1.8 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 1810 ms

> wavesurfer.js@4.4.0 build:plugins katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.plugins.js

asset wavesurfer.regions.js 41.1 KiB [compared for emit] (name: regions) 1 related asset
asset wavesurfer.spectrogram.js 23.8 KiB [compared for emit] (name: spectrogram) 1 related asset
asset wavesurfer.timeline.js 20.8 KiB [compared for emit] (name: timeline) 1 related asset
asset wavesurfer.microphone.js 15.4 KiB [compared for emit] (name: microphone) 1 related asset
asset wavesurfer.minimap.js 15.1 KiB [compared for emit] (name: minimap) 1 related asset
asset wavesurfer.cursor.js 12.6 KiB [compared for emit] (name: cursor) 1 related asset
asset wavesurfer.elan.js 12.6 KiB [compared for emit] (name: elan) 1 related asset
asset wavesurfer.mediasession.js 6.49 KiB [compared for emit] (name: mediasession) 1 related asset
modules by path ./src/plugin/regions/*.js 38.7 KiB
  ./src/plugin/regions/index.js 14.4 KiB [built] [code generated]
  ./src/plugin/regions/region.js 24.3 KiB [built] [code generated]
modules by path ./src/plugin/spectrogram/*.js 21.4 KiB
  ./src/plugin/spectrogram/index.js 15.8 KiB [built] [code generated]
  ./src/plugin/spectrogram/fft.js 5.67 KiB [built] [code generated]
./src/plugin/cursor/index.js 10.5 KiB [built] [code generated]
./src/plugin/elan/index.js 10.5 KiB [built] [code generated]
./src/plugin/mediasession/index.js 4.35 KiB [built] [code generated]
./src/plugin/microphone/index.js 13.3 KiB [built] [code generated]
./src/plugin/minimap/index.js 13 KiB [built] [code generated]
./src/plugin/timeline/index.js 18.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 1650 ms

> wavesurfer.js@4.4.0 build:htmlinit katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.htmlinit.js

asset wavesurfer-html-init.js 13.3 KiB [compared for emit] (name: html-init) 1 related asset
./src/html-init.js 9.34 KiB [built] [code generated]
./node_modules/load-script/index.js 1.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 588 ms

> wavesurfer.js@4.4.0 build:minified katspaugh-wavesurfer.js
> npm run build:main:min && npm run build:plugins:min && npm run build:htmlinit:min


> wavesurfer.js@4.4.0 build:main:min katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.main.min.js

asset wavesurfer.min.js 64.7 KiB [emitted] [minimized] (name: wavesurfer) 1 related asset
modules by path ./src/util/*.js 20.2 KiB 12 modules
modules by path ./src/*.js 167 KiB
  ./src/wavesurfer.js 60.2 KiB [built] [code generated]
  ./src/drawer.multicanvas.js 23 KiB [built] [code generated]
  ./src/webaudio.js 26.4 KiB [built] [code generated]
  ./src/mediaelement.js 17.7 KiB [built] [code generated]
  ./src/peakcache.js 4.89 KiB [built] [code generated]
  ./src/mediaelement-webaudio.js 6.61 KiB [built] [code generated]
  ./src/drawer.js 15.7 KiB [built] [code generated]
  ./src/drawer.canvasentry.js 11.9 KiB [built] [code generated]
./node_modules/debounce/index.js 1.8 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 2706 ms

> wavesurfer.js@4.4.0 build:plugins:min katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.plugins.min.js

asset wavesurfer.regions.min.js 17.4 KiB [compared for emit] [minimized] (name: regions) 1 related asset
asset wavesurfer.spectrogram.min.js 9.55 KiB [compared for emit] [minimized] (name: spectrogram) 1 related asset
asset wavesurfer.timeline.min.js 7.37 KiB [compared for emit] [minimized] (name: timeline) 1 related asset
asset wavesurfer.minimap.min.js 7.23 KiB [compared for emit] [minimized] (name: minimap) 1 related asset
asset wavesurfer.microphone.min.js 5.61 KiB [compared for emit] [minimized] (name: microphone) 1 related asset
asset wavesurfer.elan.min.js 5.42 KiB [compared for emit] [minimized] (name: elan) 1 related asset
asset wavesurfer.cursor.min.js 4.75 KiB [compared for emit] [minimized] (name: cursor) 1 related asset
asset wavesurfer.mediasession.min.js 2.24 KiB [compared for emit] [minimized] (name: mediasession) 1 related asset
modules by path ./src/plugin/regions/*.js 38.7 KiB
  ./src/plugin/regions/index.js 14.4 KiB [built] [code generated]
  ./src/plugin/regions/region.js 24.3 KiB [built] [code generated]
modules by path ./src/plugin/spectrogram/*.js 21.4 KiB
  ./src/plugin/spectrogram/index.js 15.8 KiB [built] [code generated]
  ./src/plugin/spectrogram/fft.js 5.67 KiB [built] [code generated]
./src/plugin/cursor/index.js 10.5 KiB [built] [code generated]
./src/plugin/elan/index.js 10.5 KiB [built] [code generated]
./src/plugin/mediasession/index.js 4.35 KiB [built] [code generated]
./src/plugin/microphone/index.js 13.3 KiB [built] [code generated]
./src/plugin/minimap/index.js 13 KiB [built] [code generated]
./src/plugin/timeline/index.js 18.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 1987 ms

> wavesurfer.js@4.4.0 build:htmlinit:min katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.htmlinit.min.js

asset wavesurfer-html-init.min.js 3.94 KiB [compared for emit] [minimized] (name: html-init) 1 related asset
./src/html-init.js 9.34 KiB [built] [code generated]
./node_modules/load-script/index.js 1.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 742 ms

❯ npm run build

> wavesurfer.js@4.4.0 build katspaugh-wavesurfer.js
> npm run build:normal && npm run build:minified


> wavesurfer.js@4.4.0 build:normal katspaugh-wavesurfer.js
> npm run build:main && npm run build:plugins && npm run build:htmlinit


> wavesurfer.js@4.4.0 build:main katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.main.js

asset wavesurfer.js 196 KiB [compared for emit] (name: wavesurfer) 1 related asset
modules by path ./src/util/*.js 20.2 KiB 12 modules
modules by path ./src/*.js 167 KiB
  ./src/wavesurfer.js 60.2 KiB [built] [code generated]
  ./src/drawer.multicanvas.js 23 KiB [built] [code generated]
  ./src/webaudio.js 26.4 KiB [built] [code generated]
  ./src/mediaelement.js 17.7 KiB [built] [code generated]
  ./src/peakcache.js 4.89 KiB [built] [code generated]
  ./src/mediaelement-webaudio.js 6.61 KiB [built] [code generated]
  ./src/drawer.js 15.7 KiB [built] [code generated]
  ./src/drawer.canvasentry.js 11.9 KiB [built] [code generated]
./node_modules/debounce/index.js 1.8 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 1820 ms

> wavesurfer.js@4.4.0 build:plugins katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.plugins.js

asset wavesurfer.regions.js 41.1 KiB [compared for emit] (name: regions) 1 related asset
asset wavesurfer.spectrogram.js 23.8 KiB [compared for emit] (name: spectrogram) 1 related asset
asset wavesurfer.timeline.js 20.8 KiB [compared for emit] (name: timeline) 1 related asset
asset wavesurfer.microphone.js 15.4 KiB [compared for emit] (name: microphone) 1 related asset
asset wavesurfer.minimap.js 15.1 KiB [compared for emit] (name: minimap) 1 related asset
asset wavesurfer.cursor.js 12.6 KiB [compared for emit] (name: cursor) 1 related asset
asset wavesurfer.elan.js 12.6 KiB [compared for emit] (name: elan) 1 related asset
asset wavesurfer.mediasession.js 6.49 KiB [compared for emit] (name: mediasession) 1 related asset
modules by path ./src/plugin/regions/*.js 38.7 KiB
  ./src/plugin/regions/index.js 14.4 KiB [built] [code generated]
  ./src/plugin/regions/region.js 24.3 KiB [built] [code generated]
modules by path ./src/plugin/spectrogram/*.js 21.4 KiB
  ./src/plugin/spectrogram/index.js 15.8 KiB [built] [code generated]
  ./src/plugin/spectrogram/fft.js 5.67 KiB [built] [code generated]
./src/plugin/cursor/index.js 10.5 KiB [built] [code generated]
./src/plugin/elan/index.js 10.5 KiB [built] [code generated]
./src/plugin/mediasession/index.js 4.35 KiB [built] [code generated]
./src/plugin/microphone/index.js 13.3 KiB [built] [code generated]
./src/plugin/minimap/index.js 13 KiB [built] [code generated]
./src/plugin/timeline/index.js 18.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 1636 ms

> wavesurfer.js@4.4.0 build:htmlinit katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.htmlinit.js

asset wavesurfer-html-init.js 13.3 KiB [compared for emit] (name: html-init) 1 related asset
./src/html-init.js 9.34 KiB [built] [code generated]
./node_modules/load-script/index.js 1.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 589 ms

> wavesurfer.js@4.4.0 build:minified katspaugh-wavesurfer.js
> npm run build:main:min && npm run build:plugins:min && npm run build:htmlinit:min


> wavesurfer.js@4.4.0 build:main:min katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.main.min.js

asset wavesurfer.min.js 64.7 KiB [compared for emit] [minimized] (name: wavesurfer) 1 related asset
modules by path ./src/util/*.js 20.2 KiB 12 modules
modules by path ./src/*.js 167 KiB
  ./src/wavesurfer.js 60.2 KiB [built] [code generated]
  ./src/drawer.multicanvas.js 23 KiB [built] [code generated]
  ./src/webaudio.js 26.4 KiB [built] [code generated]
  ./src/mediaelement.js 17.7 KiB [built] [code generated]
  ./src/peakcache.js 4.89 KiB [built] [code generated]
  ./src/mediaelement-webaudio.js 6.61 KiB [built] [code generated]
  ./src/drawer.js 15.7 KiB [built] [code generated]
  ./src/drawer.canvasentry.js 11.9 KiB [built] [code generated]
./node_modules/debounce/index.js 1.8 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 2734 ms

> wavesurfer.js@4.4.0 build:plugins:min katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.plugins.min.js

asset wavesurfer.regions.min.js 17.4 KiB [compared for emit] [minimized] (name: regions) 1 related asset
asset wavesurfer.spectrogram.min.js 9.55 KiB [compared for emit] [minimized] (name: spectrogram) 1 related asset
asset wavesurfer.timeline.min.js 7.37 KiB [compared for emit] [minimized] (name: timeline) 1 related asset
asset wavesurfer.minimap.min.js 7.23 KiB [compared for emit] [minimized] (name: minimap) 1 related asset
asset wavesurfer.microphone.min.js 5.61 KiB [compared for emit] [minimized] (name: microphone) 1 related asset
asset wavesurfer.elan.min.js 5.42 KiB [compared for emit] [minimized] (name: elan) 1 related asset
asset wavesurfer.cursor.min.js 4.75 KiB [compared for emit] [minimized] (name: cursor) 1 related asset
asset wavesurfer.mediasession.min.js 2.24 KiB [compared for emit] [minimized] (name: mediasession) 1 related asset
modules by path ./src/plugin/regions/*.js 38.7 KiB
  ./src/plugin/regions/index.js 14.4 KiB [built] [code generated]
  ./src/plugin/regions/region.js 24.3 KiB [built] [code generated]
modules by path ./src/plugin/spectrogram/*.js 21.4 KiB
  ./src/plugin/spectrogram/index.js 15.8 KiB [built] [code generated]
  ./src/plugin/spectrogram/fft.js 5.67 KiB [built] [code generated]
./src/plugin/cursor/index.js 10.5 KiB [built] [code generated]
./src/plugin/elan/index.js 10.5 KiB [built] [code generated]
./src/plugin/mediasession/index.js 4.35 KiB [built] [code generated]
./src/plugin/microphone/index.js 13.3 KiB [built] [code generated]
./src/plugin/minimap/index.js 13 KiB [built] [code generated]
./src/plugin/timeline/index.js 18.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 1976 ms

> wavesurfer.js@4.4.0 build:htmlinit:min katspaugh-wavesurfer.js
> webpack --config ./build-config/webpack.prod.htmlinit.min.js

asset wavesurfer-html-init.min.js 3.94 KiB [compared for emit] [minimized] (name: html-init) 1 related asset
./src/html-init.js 9.34 KiB [built] [code generated]
./node_modules/load-script/index.js 1.6 KiB [built] [code generated]
webpack 5.17.0 compiled successfully in 753 ms
```

**Comment by sundayz** [comment]
Build works fine it's probably just a problem on my end, I'll clone everything again later, didnt mean to derail your PR with that

**Comment by thijstriemstra** [comment]
> Build works fine it's probably just a problem on my end, I'll clone everything again later, didnt mean to derail your PR with that

Please open a new ticket, I'm not able to run it either, something with an ipv6 address..

**Comment by johnpaulmedina** [comment]
Ah ok. Well it runs for me using `npm run start`. However I noticed you have a double /dist/ on the ./build-config/fragments/dev.js because when using path.resolve you are going up the tree twice which brings you to the root but on your publicPath you are expecting `/dist/` so that would mean: `http://localhost:8080/dist/dist`

Just change the path.resolve to: `path.resolve(__dirname, '..', '..', 'dist')`

```
/* eslint-env node */

const path = require('path');

module.exports = {
    mode: 'development',
    devtool: 'eval-source-map',
    output: {
        publicPath: 'localhost:8080/dist/'
    },
    devServer: {
        static: [
            {
                directory: path.resolve(__dirname, '..', '..', 'dist'),
                staticOptions: {},
                publicPath: '/dist/',
                serveIndex: true,
                watch: {
                    ignored: [
                        /.chrome/,
                        /node_modules/,
                        /bower_components/,
                        /coverage/,
                        /docs/,
                        /spec/
                    ]
                }
            }
        ]
    }
};

```

**Comment by thijstriemstra** [comment]
@johnpaulmedina thanks for the feedback, please open a separate pr for that fix if you can.

**Comment by johnpaulmedina** [comment]
@thijstriemstra So I had opened a separate PR, however the forked repo was originally just for the bug fix so I had pushed on the master branch. Since I had opened this PR essentially my master branch already contains the above changes and since we had already discussed the webpack issue here - I closed the other PR #2172 and and pushed here. 

Sorry if that messes up your flow.

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks, can you also add a changelog entry (with reference to #2161)?

**Comment by johnpaulmedina** [comment]
All set

**Comment by johnpaulmedina** [comment]
Can we get this merged in?

**Review by thijstriemstra — APPROVED** [review]
thanks.

**Pull request merged**
