### PR TITLE
cursor plugin: fix displayed time

### PR DESCRIPTION
**Pull request by MichalSzorad**
### Short description of changes:
Fix computation of timeValue in CursorPlugin 

### Breaking in the external API:
\-

### Breaking changes in the internal API:
\-

### Todos/Notes:
\-

### Related Issues and other PRs:
\-

### CODE REVIEW

**Comment by thijstriemstra** [comment]
thanks!

**Comment by Vaberer** [comment]
Hey @thijstriemstra, is it possible to create a release for this fix? Last release was in November 19 and our engineers are waiting for this change.

Many thanks!

Best, Patrik

**Comment by thijstriemstra** [comment]
@Vaberer see #1545 and ping @katspaugh another time.

**Comment by Vaberer** [comment]
Hey @katspaugh , is it possible to accept a release in #1545 with this fix? Last release was in November 19 and our engineers are waiting for this change.

Many thanks!

Best, Patrik

**Pull request merged**
