### PR TITLE
Create FUNDING.yml

### LINKED ISSUE #2622: Add sponsors option
Github provides support for sponsoring projects: https://github.com/sponsors

cc @katspaugh

### PR DESCRIPTION
**Pull request by katspaugh**
Resolves #2622.

My account has been approved, so we can add a Sponsors button to this repo.

### CODE REVIEW

**Review by thijstriemstra — APPROVED** [review]
thanks @katspaugh! Should this be advertised in the readme? How will it show up on github?

**Comment by katspaugh** [comment]
I think it will add a button somewhere in the UI.

The Sponsors account seems to belong to a user, not a repo, though. So you should make an account too. I'm not 💯 sure how it works.

**Comment by thijstriemstra** [comment]
> The Sponsors account seems to belong to a user, not a repo, though. 

Yea, I only see your username as an option to sponsor. 

>  So you should make an account too.

I already have an account..

> sure how it works.

Neither do I.

**Comment by entonbiba** [comment]
@katspaugh yea it's per account, I already created one as well. Not sure if you can add multiple devs to the sponsors list?

**Comment by thijstriemstra** [comment]
I don't think it makes sense to have multiple devs in a sponsor list, ideally it should be some sort of organization that unites all devs and funds.

**Comment by katspaugh** [comment]
Good idea, @thijstriemstra. It looks like it's possible for an org to to join a "fiscal host" like https://opencollective.com/europe, which takes care of the payouts.

**Comment by katspaugh** [comment]
I've created an org, moved the repo there and invited you guys.

**Comment by thijstriemstra** [comment]
@katspaugh thanks. Could you also enable opencollective for this repository like you did with github sponsors? That github sponsors option can also be removed then.

**Comment by katspaugh** [comment]
They work together. Once they approve us, I’ll connect that account to sponsors for the new GH org, and replace the username in the md file to the org name.

**Comment by katspaugh** [comment]
An update: OC approved us, and I've submitted a new GH Sponsors request for the new org. It will take a while.

**Comment by katspaugh** [comment]
On it.

**Comment by entonbiba** [comment]
thanks!

**Pull request merged**
