### PR TITLE
fix spectrogram plugin frequency labels position

### PR DESCRIPTION
**Pull request by entonbiba**
fix spectrogram plugin frequency labels position `absolute`

### CODE REVIEW

**Comment by thijstriemstra** [comment]
we should have some unit tests one day that verify these changes, e.g. a png image with the expected output of the waveform.

**Comment by thijstriemstra** [comment]
Anyway, can you add a comment on the line above explaining why it should be `absolute`, and then I'll approve it.

**Comment by entonbiba** [comment]
@thijstriemstra, currently:
image


with the absolute fix
image

**Comment by thijstriemstra** [comment]
Thanks!

**Pull request merged**
