### PR TITLE
Fixes cut off waveform rendering

### PR DESCRIPTION
**Pull request by entonbiba**
Opening a new pr since old one had too many merges committed #1114 . This will have to be merged in order to fix the issue below.

fixes render waveform with peaks.
#1067 #1055 #1175 #1181

preview: https://codepen.io/entonbiba/pen/PmpXqJ

waveform-error

to

waveform-test

### CODE REVIEW

**Comment by mspae** [comment]
Check this: https://codepen.io/mspae/pen/Jyyxjx

the first waveform does not show the scrollbar (only upon clicking play does it render it)

I haven't tested scrolling and resizing in this scenario

**Comment by entonbiba** [comment]
@mspae it seems it needs a click for it to render the scrollbar for the first one, I'll look into it

**Comment by mspae** [comment]
I've got a fix. Just preparing a PR. Wow. that was arduous :p

**Comment by mspae** [comment]
I'll close this. since #1198 was merged.

**Comment by X-Raym** [comment]
Oh cool ! So this problem is fixed now ? :)

**Comment by mspae** [comment]
@X-Raym should be, see #1181

**Comment by awenger63** [comment]
Hello, I just begining to test your nice wavesurfer (v2.0.0-beta01) with peaks generated by audiowaveform in 16bits. 
When the wave is rendered in load function with peaks this is make 2 time => the fisrt time, just the begining part (like issue #1181 ) is visible and in second time (1 or 2 seconds later) the rest of the wave will be display (I thniks it's a redraw call).
I look change code of this closed issue, and i see it's not the same on actual version the 2.0.0 (line 3965 of wavesurfer.js). I change it to test in a local version to have the same (width*end) and the wave is correctly display in one time with the peaks ! BUT with this same code if i call load without peaks, only with song file mp3 => there is no wave :-(
Do you know if it's possible to have a solution applied who work whith and without peaks ?
Thanks a lot

**Pull request closed without merging**
