### PR TITLE
Added custom time formatter callback

### PR DESCRIPTION
**Pull request by nabiulin**

### CODE REVIEW

**Comment by nabiulin** [comment]
Hi. Faced with time format issue for long recordings.
Default time format is "minutes:seconds" and it is a little bit hard to find out the original time value.
Added time format callback for such situations.
Could you please take a look?

**Comment by katspaugh** [comment]
Thanks! :thumbsup:

**Comment by nabiulin** [comment]
Cool.Thx)Could you also rebuild minified version and update the library on bower?

**Comment by katspaugh** [comment]
I did.

**Comment by nabiulin** [comment]
Thanks a lot!

2016-01-22 21:41 GMT+02:00 katspaugh <notifications@github.com>:

**Pull request merged**
