### PR TITLE
Plugin inheritance example updated

### PR DESCRIPTION
**Pull request by marizuccara**
### Short description of changes:
Updated example of plugin inheritance because after removing all private methods of plugins, a custom plugin can be extended without duplicating code related to private methods.

### Related Issues and other PRs:
#1928

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ps. @marizuccara it looks like you misspelled your emailaddress that git on your machine is using: `Co-authored-by: marizuccara <mari.zuccara@mail.com>`. Should probably be gmail.com?

**Comment by marizuccara** [comment]
> ps. @marizuccara it looks like you misspelled your emailaddress that git on your machine is using: `Co-authored-by: marizuccara <mari.zuccara@mail.com>`. Should probably be gmail.com?

Hi yes, it's gmail account. But where I have to fix this? In the github account I see the correct mail..

**Comment by thijstriemstra** [comment]
@marizuccara take a look at https://alvinalexander.com/git/git-show-change-username-email-address/

**Comment by marizuccara** [comment]
Thanks  :)

**Comment by thijstriemstra** [comment]
no worries! I will remove these comments now it's fixed.

**Pull request merged**
