### PR TITLE
Fix: [Spectrogram] fix cropping and scaling issues

### LINKED ISSUE #3663: fftSamples shouldn't scale the spectrogram image
## Bug description
On the page [https://wavesurfer.xyz/examples/?spectrogram.js](https://wavesurfer.xyz/examples/?spectrogram.js), set the **Spectrogram** plugin option **fftSamples** from 1024 to 128 (or others), the height of the spectrogram image will change.

## Environment
 - Browser: Chrome

## Expected result
The **fftSamples** parameter only affects the resolution of the image, not its height.
I think the final image should be stretched to cover the whole range.
If the sample rate is 48000Hz, the image should always cover 0 - 24000Hz, independent of **fftSamples**.
The lower **fftSamples** means the highlights in the image will be more blur, more like a mosaic effect.

## Screenshots
image
image

### PR DESCRIPTION
**Pull request by jonom**
## Short description

Resolves #3663, #3140

## Implementation details

I've attempted to address some issues with the spectrogram rendering creating an image of the wrong height for the target container, causing it to be too tall or short to fill the area, and meaning the frequency labels do not line up with data in the image. There are some magic numbers in here (E.g. division by 2 or 4) I don't understand so appreciate if someone else can vet this!

(Marked as draft for now as I'm running tests locally but it's taking quite a while.)

Separate to this I've implemented some caching of the result of `getFrequencies()` as well as the rendered bitmaps as this can be quite slow, and for my use case we allow zooming in and out so I wanted to speed up the rendering. If this is something you'd like included I can add to this PR or open another one later.

## Checklist
* [ ] This PR is covered by e2e tests
* [x] It introduces no breaking API changes

## Summary by CodeRabbit

- **New Features**
	- Enhanced audio playback quality with an updated sample rate.
	- Added new configuration options for the Spectrogram, including frequency range and scale settings.
- **Bug Fixes**
	- Improved error handling for color map validation.
- **Refactor**
	- Streamlined frequency scaling and rendering logic in the Spectrogram plugin.

### CODE REVIEW

**Comment by katspaugh** [comment]
@jonom thanks for the PR! How did your tests go, did it solve those issues for you?

**Comment by jonom** [comment]
I'm not exactly sure how the e2e tests are supposed to be ran - after a while I worked out I could run them manually, but I didn't see snapshots to compare with expected results.

One thing I have found since is that setting sampleRate on the ws instance doesn't seem to affect rendering, except that if it's too small, the upper range of the spectrogram may be missing. So I've been setting it to 88200 and then it seems to always work 🤷‍♂️

**Comment by katspaugh** [comment]
I've commented out Spectrogram tests for now, they mysteriously always fail on GitHub Actions but work locally.

**Comment by abbott** [comment]
Howdy, the current state of the spectrogram height is broken. The current v7 library renders inconsistent height values in the DOM, which is a struggle to produce a basic spectrogram visual. 

```
<div id="spectrogram" style="width: 100%;">
    <div style="display: block; position: relative; user-select: none; width: 100%; overflow: hidden; height: 64px;">
        <canvas part="spec-labels" style="position: absolute; z-index: 9; width: 55px; height: 100%;" height="128" width="110"></canvas>
        <canvas style="position: absolute; left: 0px; top: 0px; width: 100%; height: 100%; z-index: 4;" width="537" height="64"></canvas>
    </div>
</div>
```

Does the spectrogram have other dependencies? I have followed conversations on sample rate, but it's unclear if those are hacks?

```
SpectrogramPlugin.create({
          container: "#spectrogram",
          labels: true,
          height: 80,
          ...
```

**Comment by jonom** [comment]
@katspaugh sorry for the slow reply, I didn't realise the Mel scale had been added and the fixes I supplied previously only worked for the Linear scale. I've worked with @lucastheis to update the fixes and the Mel scale should work a lot better now, being rendered at the appropriate height and also fixing a few bugs with the scale labels.

If you could let me know what I would need to do to get this over the line that would be great. No rush - I'll be off until the new year now. If you're taking some time off as well, happy holidays!

image

**Review by katspaugh — APPROVED** [review]
Amazing, thank you! Happy holidays to you as well!

**Pull request merged**
