### PR TITLE
Add version info banner

### PR DESCRIPTION
**Pull request by thijstriemstra**
The version info banner was missing from files in `dist` folder.

### CODE REVIEW

**Comment by thijstriemstra** [comment]
ping @katspaugh

**Comment by thijstriemstra** [comment]
another attempt: ping @katspaugh (perhaps you can give me merge rights?)

**Comment by katspaugh** [comment]
@thijstriemstra hey, sorry, missed your message. Adding rights!

**Comment by thijstriemstra** [comment]
Thanks mate!

**Pull request merged**
