### PR TITLE
Readme: add info about a 10-year NFT

### PR DESCRIPTION
**Pull request by katspaugh**
I've created an NFT on Polygon that represents the initial commit to this repo.
I think it would be a nice way to support the project and celebrate the 10 years.
WDYT, @thijstriemstra?

### CODE REVIEW

**Comment by thijstriemstra** [comment]
please explain how this would work. ps i think nft's is one of the dumbest and most disingenuous technological concepts ever created.

**Comment by katspaugh** [comment]
It will work like a regular donation, just with a symbolic token granted to the donator.

If it gets sold I'd be happy to send you 50% (0.5 ETH). Just tell me your wallet address. If you don't have one yet, [Metamask](https://metamask.io) is a good option.

**Comment by thijstriemstra** [comment]
because im against nft's shouldn't stop the project from participating in this area so give it a try; if it doesn't get picked up within a year, let's remove it again from the readme nxt year. 1 eth seems cheap though ;)

**Review by thijstriemstra — APPROVED** [review]

**Comment by thijstriemstra** [comment]
and i can give you a wallet address if you email me once it's sold. email can be found in git log.

**Comment by katspaugh** [comment]
Perfect, thank you! 😄

**Pull request merged**
