### PR TITLE
markers plugin: trigger click event on wavesurfer

### PR DESCRIPTION
**Pull request by Wangbaogang**
### Short description of changes:

Changes: When you click `labelDiv`, the `marker-click`event of wavesurfer is triggered (not previously).

Reasons:  In fact, when I want to do more when I click on marker, event is necessary

### Breaking in the external API:

No

### Breaking changes in the internal API:

No

### CODE REVIEW

**Comment by osheroff** [comment]
Offhand I'd say we probably don't want to fire a general "click" event, consumers will probably mostly be treating those as clicking inside the waveform.

I like the marker-click one tho

**Comment by thijstriemstra** [comment]
> I like the marker-click one tho

So what do you suggest for @Wangbaogang to follow up with?

**Comment by osheroff** [comment]
I think just remove the wavesurfer-level click event

**Comment by Wangbaogang** [comment]
@osheroff In fact, using `marker-click` event on wavesurfer is a handy way, just like `region-click` of `RegionsPlugin`, I think.

**Comment by osheroff** [comment]
I'm talking about this line:

```
            this.fireEvent("click", e);
```

I think this line is problematic as it will appear to an event listener that the user clicked on the waveform, which they did not.

**Comment by thijstriemstra** [comment]
The new event also needs to be documented (at top of class) and a changelog entry needs to be added.

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
@Wangbaogang 

- the new event needs to be documented (at top of class)
- a changelog entry needs to be added
- remove the `click` fireEvent

**Comment by Wangbaogang** [comment]
> @Wangbaogang
> 
> * the new event needs to be documented (at top of class)
> * a changelog entry needs to be added
> * remove the `click` fireEvent

Added changelog and removed click. But It seems there is no place to edit the plugin information in the repo. Maybe I didn't find it?

**Comment by thijstriemstra** [comment]
> there is no place to edit the plugin information in the repo

@Wangbaogang it's in the `gh-pages` branch. Also add a jsdoc for the new event.

**Review by thijstriemstra — APPROVED** [review]
thanks!

**Pull request merged**
