### PR TITLE
Wrap drawing in requestAnimationFrame.

### PR DESCRIPTION
**Pull request by agamemnus**
Wrap drawing in requestAnimationFrame per https://github.com/katspaugh/wavesurfer.js/issues/1084.

Blocked by https://github.com/katspaugh/wavesurfer.js/pull/1107.

### CODE REVIEW

**Comment by agamemnus** [comment]
I guess this should be merged with the other one.

**Comment by katspaugh** [comment]
Can you somehow add those `requestAnimationFrame`s on top of the existing function calls?

I.e. instead of 

```
drawSomethign: function() {
  requestAnimationFrame(function () {
    // lots of indented code
  });
}
```

This:

```
_drawSomethign: function() {
  // the original unindented code
  });
}

drawSomethign: function() {
  var my = this;
  requestAnimationFrame(function () {
    my._drawSomethign();
  });
}
```

**Comment by agamemnus** [comment]
Yes, that's possible, although I'm a little worried that the code will
become harder to understand if it has these "internal intended" properties.

Give me a few hours to wake up...

**Comment by katspaugh** [comment]
Another approach would be to wrap the definitions of the methods:

```
utils.frame = function (callback) {
  return function () {
    var my = this;
    var args = arguments;

    requestAnimationFrame(function () {
      callback.apply(my, args);
    });
  };
}

drawSomething: utils.frame(function() {
  // the original unindented code
  });
}),
```

**Comment by agamemnus** [comment]
Ok, I'll do it that way. Stay tuned...

**Comment by agamemnus** [comment]
Idk what's up.

**Comment by katspaugh** [comment]
You spread your changes over several PRs and in this PR, there's no `frame`.

**Comment by agamemnus** [comment]
Ah, okay. Idk how to combine them in the web gui.

**Comment by katspaugh** [comment]
Let's first merge the PR where you introduce these new utils.

**Comment by katspaugh** [comment]
Thank you!

**Pull request merged**
