### PR TITLE
 spectrogram plugin: fix issue where labels get stuck when scrolling

### LINKED ISSUE #2542: Frequency label display is fixed instead of absolute, which causes it to "float"
### Description
In version 6.2.0, frequency label display is fixed instead of absolute to enable consistent size on hi-dpi displays. As a result, the label "floats" as the page gets scrolled up and down

### Wavesurfer.js version(s):
6.2.0

### Browser and operating system version(s):
Chrome version Version 100.0.4896.127

### Code and behaviour needed to reproduce the issue:
See example here: https://wavesurfer-js.org/example/spectrogram/index.html
Behaves similarly in the application I am building.
Screenshot 2022-06-30 at 3 41 17 PM

### PR DESCRIPTION
**Pull request by musicog**
### Short description of changes:
Change display style property on spectrogram labels from 'fixed' to 'absolute' to correct their position when scrolling, to prevent the spectrogram from scrolling away while leaving the labels 'stuck' on their initial screen position.

To replicate the problem, go to https://wavesurfer-js.org/example/spectrogram/index.html and scroll down.

### Breaking in the external API:
No

### Breaking changes in the internal API:
No

### Todos/Notes:
Tiny change to fix what appears to clearly be a bug / unintended behaviour

### Related Issues and other PRs:
fixes #2542
#1666

### CODE REVIEW

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks @musicog 

#1666 requests an option for this. Can you implement this instead? Having `absolute` as default for that new option is fine with me. Also, please add a changelog entry.

**Comment by musicog** [comment]
Happy to try implementing an option for this if it's useful, but right now I can't see a use-case at all for position:fixed - it just seems like an outright bug to me. I'll ask @Brabudu for comment in the issue.

**Comment by thijstriemstra** [comment]
thanks for adding that comment there @musicog. If and when @Brabudu responds, we can see what to do then but I'll merge this for now.

**Comment by thijstriemstra** [comment]
oh, a changelog entry is missing, can you add that @musicog

**Comment by musicog** [comment]
CHANGES.md updated!

**Comment by thijstriemstra** [comment]
> CHANGES.md updated!

Not in this branch it seems..

**Comment by musicog** [comment]
🤦 apologies - now hopefully on the correct branch.

**Review by thijstriemstra — APPROVED** [review]

**Comment by MartinKlimes** [comment]
I guess I figured it out.
If you have one waveform + spectrogram, simply use:

```
wavesurfer.on('ready', function(){
     document.querySelector(".spec-labels").style.position = 'absolute'
})
```
In my case i had many waveforms and spectrograms saved into wavesurfer, so:

```
    wavesurfer[index].on('ready', function(){
        var labels = document.querySelectorAll(".spec-labels")
        labels.forEach(label => {
            label.style.position = 'absolute'
          });
    })

```

**Pull request merged**
