### PR TITLE
cache NPM packages on travis and add windows build

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@katspaugh can you enable appveyor for this repository so I can test the windows build with this PR?

**Comment by thijstriemstra** [comment]
ping @katspaugh

**Comment by thijstriemstra** [comment]
This is blocked until someone with proper rights (@katspaugh) enables AppVeyor for this repository.

**Comment by katspaugh** [comment]
I've authorized AppVeyor and added a new project for this repo. Please let me know if any additional action is needed.

**Comment by thijstriemstra** [comment]
thanks @katspaugh, I will.

**Comment by thijstriemstra** [comment]
Cool, windows build is working now, if it succeeds I'll merge this.

**Comment by thijstriemstra** [comment]
@mspae I fixed the windows build error, you content with my particular fix so I can merge this?

**Pull request merged**
