### PR TITLE
Minimap new functionalities (overview and regions support)

### PR DESCRIPTION
**Pull request by RocAlayo**
The regions are shown in the minimap and the minimap shows clearly which part of the wave is showing above. You can see an example [here](http://development.wavesurfer-bitbucket.divshot.io/) and the example code  [here](https://github.com/RocAlayo/example-wavesurfer.js-minimap)

### CODE REVIEW

**Comment by katspaugh** [comment]
Great work, thanks a lot!

Do you think we could later refactor the overview and regions functionality in such way that it reuses the same functionality from the regions plugin?

**Comment by RocAlayo** [comment]
I suppose we could but I don't see why we would. The region functionalities are developed to have a wavesurfer element as a base and the minimap is not a full wavesurfer element, it's just the wavesurfer drawer enhanced. In other words, I think if you want the functionalities of a wavesurfer element as a minimap just make another wavesurfer element and interconnect it with the main wavesurfer element.

**Comment by katspaugh** [comment]
Fair enough. Thank you!

**Comment by RocAlayo** [comment]
Thank you to you too. This library is great! :D

**Pull request merged**
