### PR TITLE
Add grunt serve task

### PR DESCRIPTION
**Pull request by chinshr**
Add `grunt serve` task to start local Web server for running examples.

### CODE REVIEW

**Comment by katspaugh** [comment]
It already has a `connect` task: https://github.com/chinshr/wavesurfer.js/blob/grunt-serve/Gruntfile.js#L36
Added in #511.

**Comment by chinshr** [comment]
Got it. How do you launch a server though, grunt serve did not work for me.

**Comment by katspaugh** [comment]
`grunt connect` obviously.

**Comment by chinshr** [comment]
Ahh, so easy, did not know. Thanks.

Jürgen

**Pull request closed without merging**
