### PR TITLE
add spectrum plugin

### PR DESCRIPTION
**Pull request by smolleyes**
exemple:

```
// Play on audio load
    wavesurfer.on('ready', function () {
    var spectrum = Object.create(WaveSurfer.Spectrum);

    spectrum.init({
            wavesurfer: wavesurfer,
            container: "#wave-spectrum",
            fftSamples : 512,
            colorStop1 : 'black', // base color
            colorStop2 : 'black', //middle color
            colorStop3 : 'red', // top color
            capStyle   : 'pink', // small caps on top of meters
            meterWidth : 10, //width of the meters in the spectrum
            gapSpace        : 2, //gap between meters
            capHeight  : 2 // cap height
        });
        wavesurfer.play();
});
```

thanks

### CODE REVIEW

**Comment by katspaugh** [comment]
Please fix the warnings TravisCI is giving: https://travis-ci.org/katspaugh/wavesurfer.js/builds/88567516
No need for semicolons after `if`- and `for`-blocks, and some missing semicolons.

**Comment by katspaugh** [comment]
It would also be nice if you created a demo in the `/example` folder.
Regarding the name of the plugin, I think it's a bit confusing to have `spectrum` and `spectrogram` plugins. I think yours should rather be called `RealtimeSpectrum` or something.

**Comment by smolleyes** [comment]
hi

OK i LL do that asap !

Envoyé par TypeMail



Sur 1 nov. 2015 10:53, à 10:53, katspaugh <notifications@github.com> a écrit:

**Comment by thijstriemstra** [comment]
@smolleyes any update on this?

**Pull request closed without merging**
