### PR TITLE
Cleanup npm package

### PR DESCRIPTION
**Pull request by thijstriemstra**
The current (1.3.2) npm package contains a lot of unnecessary files for an NPM user:

```
$ ls -l node_modules/wavesurfer.js/
total 60
-rw-rw-r--  1 thijs thijs  343 feb  7 12:19 bower.json
-rw-rw-r--  1 thijs thijs 1923 feb  7 12:23 CHANGES.md
-rw-rw-r--  1 thijs thijs   18 feb 14  2016 CNAME
drwxrwxr-x  4 thijs thijs 4096 feb  8 22:38 coverage
drwxrwxr-x  3 thijs thijs 4096 feb  8 22:38 dist
drwxrwxr-x 20 thijs thijs 4096 feb  8 22:38 example
-rw-rw-r--  1 thijs thijs 5481 jan 19 16:43 Gruntfile.js
-rw-rw-r--  1 thijs thijs 1302 jan 19 16:43 karma.conf.js
-rw-rw-r--  1 thijs thijs 2801 feb  8 22:38 package.json
drwxrwxr-x  2 thijs thijs 4096 feb  8 22:38 plugin
-rw-rw-r--  1 thijs thijs 4411 jan 19 16:43 README.md
drwxrwxr-x  3 thijs thijs 4096 feb  8 22:38 spec
drwxrwxr-x  2 thijs thijs 4096 feb  8 22:38 src
```

Only dist is really needed. This PR excludes everything that npm doesn't include already by default, and includes the required `dist` and optional `src` and `plugins` directories for compatibility with people currently using npm. I suggest we stop doing that after the next branch and only distribute the `dist` dir.

`npm pack` is a useful command to display what will go into the NPM package. With this PR:

```
$ npm pack
wavesurfer.js-1.3.2.tgz

$ tar -tf wavesurfer.js-1.3.2.tgz 
package/package.json
package/README.md
package/CHANGES.md
package/dist/wavesurfer.js
package/dist/wavesurfer.min.js
package/dist/plugin/wavesurfer.cursor.js
package/dist/plugin/wavesurfer.elan.min.js
package/dist/plugin/wavesurfer.microphone.js
package/dist/plugin/wavesurfer.microphone.min.js
package/dist/plugin/wavesurfer.minimap.js
package/dist/plugin/wavesurfer.elan.js
package/dist/plugin/wavesurfer.regions.js
package/dist/plugin/wavesurfer.regions.min.js
package/dist/plugin/wavesurfer.spectrogram.js
package/dist/plugin/wavesurfer.spectrogram.min.js
package/dist/plugin/wavesurfer.timeline.js
package/dist/plugin/wavesurfer.cursor.min.js
package/dist/plugin/wavesurfer.timeline.min.js
package/dist/plugin/wavesurfer.minimap.min.js
package/dist/wavesurfer.min.js.map
package/plugin/wavesurfer.cursor.js
package/plugin/wavesurfer.elan.js
package/plugin/wavesurfer.microphone.js
package/plugin/wavesurfer.minimap.js
package/plugin/wavesurfer.regions.js
package/plugin/wavesurfer.spectrogram.js
package/plugin/wavesurfer.timeline.js
package/src/drawer.canvas.js
package/src/drawer.js
package/src/drawer.multicanvas.js
package/src/html-init.js
package/src/mediaelement.js
package/src/peakcache.js
package/src/util.js
package/src/wavesurfer.js
package/src/webaudio.js
```

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@katspaugh With this PR it now randomly includes the non-minified and minified plugins though, I guess we only want the minified plugins, or do we want both versions of each plugin?

**Comment by mspae** [comment]
Awesome. I think `bower.json` is missing though.

**Comment by thijstriemstra** [comment]
Npm stripped out bower.json; not needed there.

**Comment by mspae** [comment]
Aah. Of course :)

**Comment by thijstriemstra** [comment]
@mspae can you add a github review so I can merge it (it's blocked until at least one approved review).

**Comment by mspae** [comment]
my bad. I can't review from my phone for some reason. :no_mobile_phones:

**Pull request merged**
