### PR TITLE
New Styling Options

### PR DESCRIPTION
**Pull request by gjsmith66**
Add options add background-url to Wave-Canvas, and change overFlow of
Wave container.  Also add option to override style of Region container.

### CODE REVIEW

**Comment by chinshr** [comment]
Nice! The background image could be used to show a thumb image at the current position. Would be interesting to see how to align multiple image thumbs like in video authoring software on desktops.

**Comment by gjsmith66** [comment]
Thanks, I use it to display a grid behind the wave form, like so.

slack-imgs com

**Comment by katspaugh** [comment]
Can't you just set these styles via CSS on the container? The container is supposed to be controlled by the application, isn't it?

**Comment by gjsmith66** [comment]
For the background-url, yes I suppose that it could be set using CSS style.  However I believe the overflow will be over-ridden by the element style.  Same for the Region style I think.

**Comment by gjsmith66** [comment]
Yes, I was able to make all changes I needed via CSS and using !important.  Adding the ability to add programmatically may be useful, otherwise it does appear that using CSS alone will work.

Thanks.

**Comment by katspaugh** [comment]
> Yes, I was able to make all changes I needed via CSS and using !important.

Exactly. Besides, `overflow: hidden` is already supported as the [`hideScrollbar` option](https://github.com/katspaugh/wavesurfer.js/blob/master/src/wavesurfer.js#L23).

Let's keep the API compact. We can be encourage using CSS directly in the documentation.

**Pull request closed without merging**
