### PR TITLE
release: 6.0.0

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@caugner want to take a look at the upgrade doc for 6.0.0? If you do, make the new PR against the branch of this PR.

**Comment by caugner** [comment]
@thijstriemstra I'm afraid I have very limited time these days. The changelog doesn't mention any breaking change. Are there any?

**Comment by thijstriemstra** [comment]
@caugner no worries! then consider it a heads up for a new release, in case you want to update the ts files.

**Comment by caugner** [comment]
See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58661

If I'm not mistaken, the only breaking change is the removal of `CursorPlugin.outerWidth()` in bff81af86e581412ed2b506b9fbeb706b605d663.

**Pull request merged**
