### PR TITLE
Feature: soundtouch.js filter to preserve pitch when changing tempo

### PR DESCRIPTION
**Pull request by katspaugh**
I went with the solution that @jsphweid suggested in #149. However, the wavesurfer.js code is unmodified. Soundtouch.js is connected as an external filter.

Here's a live demo: http://wavesurfer-js.org/example/stretcher/

### CODE REVIEW

**Comment by thijstriemstra** [comment]
is soundtouch available on npm? I'd rather not include it in the repo as it gets outdated quickly.

**Comment by katspaugh** [comment]
It was last updated 5 years ago 😄

**Comment by katspaugh** [comment]
@jeremylach failed to sponsor the bounty, so I'm closing this.

**Comment by wcallag3** [comment]
I utilized the code in #1157 in app.js from line 20 - 70 to preserve pitch when changing playback rate, however I still get the issue where the play cursor does not update correctly. I'm currently using Wavesurfer 1.1.1 (I know it's super old, but I can't change it right now). I've also noticed that this only works in Chrome and not Firefox. Any insight would be much appreciated.

**Comment by katspaugh** [comment]
@wcallag3 so is your issue with #1157 or with this PR?

**Comment by katspaugh** [comment]
GitHub did something weird when I tried to change the base of the PR to the current master. I'll need to update the code for the version 2.

**Comment by tyler-g** [comment]
@katspaugh I'm not exactly sure how to implement this without copying code from the demo example: http://wavesurfer-js.org/example/stretcher/

Can this be available as a plugin and added to the plugins docs?

**Comment by katspaugh** [comment]
@tyler-g good idea! Will do. Btw the stretcher example was merged in #1214.

**Comment by tyler-g** [comment]
Great!  Thanks

**Pull request closed without merging**
