### PR TITLE
Master

### PR DESCRIPTION
**Pull request by nabiulin**

### CODE REVIEW

**Comment by nabiulin** [comment]
Hi. Faced with the issue for long records. In case if record has duration more than 2 hours - time labels became extremely close to each other. Have added configurable time label params. Could you please take a look?

**Comment by nabiulin** [comment]
time-labels-issue
Here is a screenshot

**Comment by katspaugh** [comment]
Merged, thanks!

**Comment by nabiulin** [comment]
Could you also update the version and publish it to bower?

**Comment by katspaugh** [comment]
Done.

**Comment by nabiulin** [comment]
Thanks a lot!

**Pull request merged**
